export const kconfigJSON = [

  {
    id: "产品配置",
    type: "menu",
    title: "产品配置",
    children: [
      {
        id: "CL_REMOTE_CONTROL",
        help: null,
        name: "CL_REMOTE_CONTROL",
        type: "menu",
        range: null,
        title: "遥控控制",
        default: "y",
        children: [  ],
        depends_on: null,
        is_menuconfig: true,
      },
      {
        id: "产品配置--type-menu2-",
        type: "menu2",
        title: "",
        children: [
          {
            id: "CL_REMOTE_CONTROL_-id-_CODE",
            help: null,
            name: "CL_REMOTE_CONTROL_-id-_CODE",
            type: "int",
            range: null,
            title: "Code",
            default: "0",
            children: [],
            placement: "left",
            depends_on: "CL_REMOTE_CONTROL",
          },
          {
            id: "产品配置--type-menu2--fun-placement-middle-",
            help: null,
            name: "CL_REMOTE_CONTROL_-id-_FUN",
            type: "choice",
            title: "Fun",
            children: [
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_light_on",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_light_on",
                type: "bool",
                range: null,
                title: "on",
                default: "y",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_light_off",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_light_off",
                type: "bool",
                range: null,
                title: "off",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_color",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_color",
                type: "bool",
                range: null,
                title: "color",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_remote_lock_and_unlock",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_remote_lock_and_unlock",
                type: "bool",
                range: null,
                title: "lock",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_auto_scene_mode",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_auto_scene_mode",
                type: "bool",
                range: null,
                title: "auto",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_music_mode",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_music_mode",
                type: "bool",
                range: null,
                title: "音乐模式",
                children: [],
                depends_on:
                  "CL_MUSIC_MODE && <choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_countdown",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_countdown",
                type: "bool",
                range: null,
                title: "倒计时",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_speed",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_speed",
                type: "bool",
                range: null,
                title: "速度+",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_speed",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_speed",
                type: "bool",
                range: null,
                title: "速度-",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_temp",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_temp",
                type: "bool",
                range: null,
                title: "色温+",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_temp",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_temp",
                type: "bool",
                range: null,
                title: "色温-",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_bright",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_bright",
                type: "bool",
                range: null,
                title: "亮度+",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_bright",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_bright",
                type: "bool",
                range: null,
                title: "亮度-",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_scene_mode",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_scene_mode",
                type: "bool",
                range: null,
                title: "场景+",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_scene_mode",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_scene_mode",
                type: "bool",
                range: null,
                title: "场景-",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_rgb_index",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_rgb_index",
                type: "bool",
                range: null,
                title: "三色循环",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_rgb_index1",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_rgb_index1",
                type: "bool",
                range: null,
                title: "七色循环",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_cw",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_cw",
                type: "bool",
                range: null,
                title: "冷暖切换",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_custom",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_custom",
                type: "bool",
                range: null,
                title: "custom",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
            ],
            placement: "middle",
            depends_on: "CL_REMOTE_CONTROL",
          },
          {
            id: "CL_REMOTE_CONTROL_-id-_FUN_arg",
            help: null,
            name: "CL_REMOTE_CONTROL_-id-_FUN_arg",
            type: "string",
            range: null,
            title: "",
            default: '""',
            children: [],
            placement: "right",
            depends_on:
              "(CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_countdown || CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_color || CL_REMOTE_CONTROL_-id-_FUN_custom || CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_music_mode) && CL_REMOTE_CONTROL",
          },
        ],
        depends_on: "CL_REMOTE_CONTROL",
      },
    ],
    depends_on: null,
  },
];
