export const kconfigJSON = [
  {
    id: "基本信息",
    type: "menu",
    title: "基本信息",
    children: [
      {
        id: "CL_PRODUCT_NAME",
        help: null,
        name: "CL_PRODUCT_NAME",
        type: "string",
        range: null,
        title: "产品名称",
        default: '""',
        children: [],
        depends_on: null,
      },
      {
        id: "CL_HARDWARE_VERSION",
        help: null,
        name: "CL_HARDWARE_VERSION",
        type: "string",
        range: null,
        title: "硬件版本",
        default: '"1.0.0"',
        children: [],
        depends_on: null,
      },
    ],
    depends_on: null,
  },
  {
    id: "芯片模组",
    type: "menu",
    title: "芯片模组",
    children: [
      {
        id: "芯片模组-芯片",
        help: null,
        name: "CL_CHIP_TYPE",
        type: "choice",
        title: "芯片",
        children: [
          {
            id: "CL_CHIP_TYPE_NULL",
            help: null,
            name: "CL_CHIP_TYPE_NULL",
            type: "bool",
            range: null,
            title: "未设置",
            default: "y",
            children: [],
            depends_on: "<choice CL_CHIP_TYPE>",
          },
          {
            id: "CL_CHIP_TYPE_ESP32",
            help: null,
            name: "CL_CHIP_TYPE_ESP32",
            type: "bool",
            range: null,
            title: "ESP32",
            children: [],
            depends_on: "<choice CL_CHIP_TYPE>",
          },
          {
            id: "CL_CHIP_TYPE_ESP32C3",
            help: null,
            name: "CL_CHIP_TYPE_ESP32C3",
            type: "bool",
            range: null,
            title: "ESP32C3",
            children: [],
            depends_on: "<choice CL_CHIP_TYPE>",
          },
          {
            id: "CL_CHIP_TYPE_ESP8685",
            help: null,
            name: "CL_CHIP_TYPE_ESP8685",
            type: "bool",
            range: null,
            title: "ESP8685",
            children: [],
            depends_on: "<choice CL_CHIP_TYPE>",
          },
          {
            id: "CL_CHIP_TYPE_ESP8684",
            help: null,
            name: "CL_CHIP_TYPE_ESP8684",
            type: "bool",
            range: null,
            title: "ESP8684",
            children: [],
            depends_on: "<choice CL_CHIP_TYPE>",
          },
          {
            id: "CL_CHIP_TYPE_BL602C",
            help: null,
            name: "CL_CHIP_TYPE_BL602C",
            type: "bool",
            range: null,
            title: "BL602C",
            children: [],
            depends_on: "<choice CL_CHIP_TYPE>",
          },
          {
            id: "CL_CHIP_TYPE_BL602L",
            help: null,
            name: "CL_CHIP_TYPE_BL602L",
            type: "bool",
            range: null,
            title: "BL602L",
            children: [],
            depends_on: "<choice CL_CHIP_TYPE>",
          },
          {
            id: "CL_CHIP_TYPE_LN882H",
            help: null,
            name: "CL_CHIP_TYPE_LN882H",
            type: "bool",
            range: null,
            title: "LN882H",
            children: [],
            depends_on: "<choice CL_CHIP_TYPE>",
          },
        ],
        depends_on: null,
      },
      {
        id: "芯片模组-esp32模组",
        help: null,
        name: "CL_ESP32_MODULE",
        type: "choice",
        title: "ESP32模组",
        children: [
          {
            id: "CL_ESP32_MODULE_NULL",
            help: null,
            name: "CL_ESP32_MODULE_NULL",
            type: "bool",
            range: null,
            title: "不使用模组",
            default: "y",
            children: [],
            depends_on: "<choice CL_ESP32_MODULE>",
          },
          {
            id: "CL_ESP32_MODULE_ESP_HOME",
            help: null,
            name: "CL_ESP32_MODULE_ESP_HOME",
            type: "bool",
            range: null,
            title: "ESP-HOME",
            children: [],
            depends_on: "<choice CL_ESP32_MODULE>",
          },
          {
            id: "CL_ESP32_MODULE_ESP_02",
            help: null,
            name: "CL_ESP32_MODULE_ESP_02",
            type: "bool",
            range: null,
            title: "ESP-02",
            children: [],
            depends_on: "<choice CL_ESP32_MODULE>",
          },
        ],
        depends_on: "CL_CHIP_TYPE_ESP32",
      },
      {
        id: "芯片模组-esp32c3模组",
        help: null,
        name: "CL_ESP32C3_MODULE",
        type: "choice",
        title: "ESP32C3模组",
        children: [
          {
            id: "CL_ESP32C3_MODULE_NULL",
            help: null,
            name: "CL_ESP32C3_MODULE_NULL",
            type: "bool",
            range: null,
            title: "不使用模组",
            default: "y",
            children: [],
            depends_on: "<choice CL_ESP32C3_MODULE>",
          },
          {
            id: "CL_ESP32C3_MODULE_ESP_C02",
            help: null,
            name: "CL_ESP32C3_MODULE_ESP_C02",
            type: "bool",
            range: null,
            title: "ESP-C02",
            children: [],
            depends_on: "<choice CL_ESP32C3_MODULE>",
          },
          {
            id: "CL_ESP32C3_MODULE_ESP_C05",
            help: null,
            name: "CL_ESP32C3_MODULE_ESP_C05",
            type: "bool",
            range: null,
            title: "ESP-C05",
            children: [],
            depends_on: "<choice CL_ESP32C3_MODULE>",
          },
          {
            id: "CL_ESP32C3_MODULE_ESP_C12",
            help: null,
            name: "CL_ESP32C3_MODULE_ESP_C12",
            type: "bool",
            range: null,
            title: "ESP-C12",
            children: [],
            depends_on: "<choice CL_ESP32C3_MODULE>",
          },
        ],
        depends_on: "CL_CHIP_TYPE_ESP32C3",
      },
      {
        id: "芯片模组-esp8685模组",
        help: null,
        name: "CL_ESP8685_MODULE",
        type: "choice",
        title: "ESP8685模组",
        children: [
          {
            id: "CL_ESP8685_MODULE_NULL",
            help: null,
            name: "CL_ESP8685_MODULE_NULL",
            type: "bool",
            range: null,
            title: "不使用模组",
            default: "y",
            children: [],
            depends_on: "<choice CL_ESP8685_MODULE>",
          },
          {
            id: "CL_ESP8685_MODULE_ESP_C02M",
            help: null,
            name: "CL_ESP8685_MODULE_ESP_C02M",
            type: "bool",
            range: null,
            title: "ESP-C02M",
            children: [],
            depends_on: "<choice CL_ESP8685_MODULE>",
          },
          {
            id: "CL_ESP8685_MODULE_ESP_C05M",
            help: null,
            name: "CL_ESP8685_MODULE_ESP_C05M",
            type: "bool",
            range: null,
            title: "ESP-C05M",
            children: [],
            depends_on: "<choice CL_ESP8685_MODULE>",
          },
          {
            id: "CL_ESP8685_MODULE_ESP_C12M",
            help: null,
            name: "CL_ESP8685_MODULE_ESP_C12M",
            type: "bool",
            range: null,
            title: "ESP-C12M",
            children: [],
            depends_on: "<choice CL_ESP8685_MODULE>",
          },
        ],
        depends_on: "CL_CHIP_TYPE_ESP8685",
      },
      {
        id: "芯片模组-esp8684模组",
        help: null,
        name: "CL_ESP8684_MODULE",
        type: "choice",
        title: "ESP8684模组",
        children: [
          {
            id: "CL_ESP8684_MODULE_NULL",
            help: null,
            name: "CL_ESP8684_MODULE_NULL",
            type: "bool",
            range: null,
            title: "不使用模组",
            default: "y",
            children: [],
            depends_on: "<choice CL_ESP8684_MODULE>",
          },
          {
            id: "CL_ESP8684_MODULE_ESPC2_01",
            help: null,
            name: "CL_ESP8684_MODULE_ESPC2_01",
            type: "bool",
            range: null,
            title: "ESPC2-01",
            children: [],
            depends_on: "<choice CL_ESP8684_MODULE>",
          },
          {
            id: "CL_ESP8684_MODULE_ESPC2_02",
            help: null,
            name: "CL_ESP8684_MODULE_ESPC2_02",
            type: "bool",
            range: null,
            title: "ESPC2-02",
            children: [],
            depends_on: "<choice CL_ESP8684_MODULE>",
          },
          {
            id: "CL_ESP8684_MODULE_ESPC2_05",
            help: null,
            name: "CL_ESP8684_MODULE_ESPC2_05",
            type: "bool",
            range: null,
            title: "ESPC2-05",
            children: [],
            depends_on: "<choice CL_ESP8684_MODULE>",
          },
          {
            id: "CL_ESP8684_MODULE_ESPC2_12",
            help: null,
            name: "CL_ESP8684_MODULE_ESPC2_12",
            type: "bool",
            range: null,
            title: "ESPC2-12",
            children: [],
            depends_on: "<choice CL_ESP8684_MODULE>",
          },
        ],
        depends_on: "CL_CHIP_TYPE_ESP8684",
      },
      {
        id: "芯片模组-bl602c模组",
        help: null,
        name: "CL_BL602C_MODULE",
        type: "choice",
        title: "BL602C模组",
        children: [
          {
            id: "CL_BL602C_MODULE_NULL",
            help: null,
            name: "CL_BL602C_MODULE_NULL",
            type: "bool",
            range: null,
            title: "不使用模组",
            default: "y",
            children: [],
            depends_on: "<choice CL_BL602C_MODULE>",
          },
          {
            id: "CL_BL602C_MODULE_BL10_2M",
            help: null,
            name: "CL_BL602C_MODULE_BL10_2M",
            type: "bool",
            range: null,
            title: "BL10_2M",
            children: [],
            depends_on: "<choice CL_BL602C_MODULE>",
          },
        ],
        depends_on: "CL_CHIP_TYPE_BL602C",
      },
      {
        id: "芯片模组-bl602l模组",
        help: null,
        name: "CL_BL602L_MODULE",
        type: "choice",
        title: "BL602L模组",
        children: [
          {
            id: "CL_BL602L_MODULE_NULL",
            help: null,
            name: "CL_BL602L_MODULE_NULL",
            type: "bool",
            range: null,
            title: "不使用模组",
            default: "y",
            children: [],
            depends_on: "<choice CL_BL602L_MODULE>",
          },
          {
            id: "CL_BL602L_MODULE_BL200_1M",
            help: null,
            name: "CL_BL602L_MODULE_BL200_1M",
            type: "bool",
            range: null,
            title: "BL200_1M",
            children: [],
            depends_on: "<choice CL_BL602L_MODULE>",
          },
          {
            id: "CL_BL602L_MODULE_BL02_1M",
            help: null,
            name: "CL_BL602L_MODULE_BL02_1M",
            type: "bool",
            range: null,
            title: "BL02_1M",
            children: [],
            depends_on: "<choice CL_BL602L_MODULE>",
          },
          {
            id: "CL_BL602L_MODULE_BL12_1M",
            help: null,
            name: "CL_BL602L_MODULE_BL12_1M",
            type: "bool",
            range: null,
            title: "BL12_1M",
            children: [],
            depends_on: "<choice CL_BL602L_MODULE>",
          },
          {
            id: "CL_BL602L_MODULE_BL12_2M",
            help: null,
            name: "CL_BL602L_MODULE_BL12_2M",
            type: "bool",
            range: null,
            title: "BL12_2M",
            children: [],
            depends_on: "<choice CL_BL602L_MODULE>",
          },
        ],
        depends_on: "CL_CHIP_TYPE_BL602L",
      },
      {
        id: "芯片模组-ln882h模组",
        help: null,
        name: "CL_LN882H_MODULE",
        type: "choice",
        title: "LN882H模组",
        children: [
          {
            id: "CL_LN882H_MODULE_NULL",
            help: null,
            name: "CL_LN882H_MODULE_NULL",
            type: "bool",
            range: null,
            title: "不使用模组",
            default: "y",
            children: [],
            depends_on: "<choice CL_LN882H_MODULE>",
          },
          {
            id: "CL_LN882H_MODULE_LN_02",
            help: null,
            name: "CL_LN882H_MODULE_LN_02",
            type: "bool",
            range: null,
            title: "LN-02",
            children: [],
            depends_on: "<choice CL_LN882H_MODULE>",
          },
          {
            id: "CL_LN882H_MODULE_LN_05",
            help: null,
            name: "CL_LN882H_MODULE_LN_05",
            type: "bool",
            range: null,
            title: "LN-05",
            children: [],
            depends_on: "<choice CL_LN882H_MODULE>",
          },
          {
            id: "CL_LN882H_MODULE_LN_10",
            help: null,
            name: "CL_LN882H_MODULE_LN_10",
            type: "bool",
            range: null,
            title: "LN-10",
            children: [],
            depends_on: "<choice CL_LN882H_MODULE>",
          },
        ],
        depends_on: "CL_CHIP_TYPE_LN882H",
      },
    ],
    depends_on: null,
  },
  {
    id: "产品配置",
    type: "menu",
    title: "产品配置",
    children: [
      {
        id: "产品配置-灯的类型",
        help: null,
        name: "CL_LIGHT_TYPE",
        type: "choice",
        title: "灯的类型",
        children: [
          {
            id: "CL_LIGHT_TYPE_BULB_LIGHT",
            help: null,
            name: "CL_LIGHT_TYPE_BULB_LIGHT",
            type: "bool",
            range: null,
            title: "球泡灯",
            default: "y",
            children: [],
            depends_on: "<choice CL_LIGHT_TYPE>",
          },
          {
            id: "CL_LIGHT_TYPE_CEILING_LIGHT",
            help: null,
            name: "CL_LIGHT_TYPE_CEILING_LIGHT",
            type: "bool",
            range: null,
            title: "吸顶灯",
            children: [],
            depends_on: "<choice CL_LIGHT_TYPE>",
          },
          {
            id: "CL_LIGHT_TYPE_MUSIC_STRIP",
            help: null,
            name: "CL_LIGHT_TYPE_MUSIC_STRIP",
            type: "bool",
            range: null,
            title: "灯带",
            children: [],
            depends_on: "<choice CL_LIGHT_TYPE>",
          },
        ],
        depends_on: null,
      },
      {
        id: "产品配置-rgbcw",
        type: "menu",
        title: "RGBCW",
        children: [
          {
            id: "产品配置-rgbcw-rgbcw信道",
            help: null,
            name: "CL_LIGHT_RGBCW_TYPE",
            type: "choice",
            title: "RGBCW信道",
            children: [
              {
                id: "CL_LIGHT_C",
                help: null,
                name: "CL_LIGHT_C",
                type: "bool",
                range: null,
                title: "C",
                children: [],
                depends_on: "<choice CL_LIGHT_RGBCW_TYPE>",
              },
              {
                id: "CL_LIGHT_CW",
                help: null,
                name: "CL_LIGHT_CW",
                type: "bool",
                range: null,
                title: "CW",
                children: [],
                depends_on: "<choice CL_LIGHT_RGBCW_TYPE>",
              },
              {
                id: "CL_LIGHT_RGB",
                help: null,
                name: "CL_LIGHT_RGB",
                type: "bool",
                range: null,
                title: "RGB",
                children: [],
                depends_on: "<choice CL_LIGHT_RGBCW_TYPE>",
              },
              {
                id: "CL_LIGHT_RGBC",
                help: null,
                name: "CL_LIGHT_RGBC",
                type: "bool",
                range: null,
                title: "RGBC",
                children: [],
                depends_on: "<choice CL_LIGHT_RGBCW_TYPE>",
              },
              {
                id: "CL_LIGHT_RGBCW",
                help: null,
                name: "CL_LIGHT_RGBCW",
                type: "bool",
                range: null,
                title: "RGBCW",
                default: "y",
                children: [],
                depends_on: "<choice CL_LIGHT_RGBCW_TYPE>",
              },
            ],
            depends_on: null,
          },
          {
            id: "CL_LIGHT_USE_PWM_DRIVER",
            help: null,
            name: "CL_LIGHT_USE_PWM_DRIVER",
            type: "menu",
            range: null,
            title: "PWM驱动",
            default: "y",
            children: [
              {
                id: "CL_LIGHT_USE_PWM_DRIVER",
                help: null,
                name: "CL_LIGHT_USE_PWM_DRIVER",
                type: "bool",
                range: null,
                title: "PWM驱动",
                default: "y",
                children: [],
                depends_on: null,
                is_menuconfig: true,
              },
              {
                id: "CL_LIGHT_PWM_DRIVER_FREQ",
                help: null,
                name: "CL_LIGHT_PWM_DRIVER_FREQ",
                type: "int",
                range: [10, 20000],
                title: "PWM频率",
                default: "5000",
                children: [],
                depends_on: "CL_LIGHT_USE_PWM_DRIVER",
              },
              {
                id: "CL_LIGHT_PWM_DRIVER_ACTIVE_LEVEL_HIGH",
                help: null,
                name: "CL_LIGHT_PWM_DRIVER_ACTIVE_LEVEL_HIGH",
                type: "bool",
                range: null,
                title: "高电平有效",
                default: "y",
                children: [],
                depends_on: "CL_LIGHT_USE_PWM_DRIVER",
              },
            ],
            depends_on: null,
            is_menuconfig: true,
          },
          {
            id: "CL_LIGHT_USE_IIC_DRIVER",
            help: null,
            name: "CL_LIGHT_USE_IIC_DRIVER",
            type: "menu",
            range: null,
            title: "使能IIC驱动",
            default: "n",
            children: [
              {
                id: "CL_LIGHT_USE_IIC_DRIVER",
                help: null,
                name: "CL_LIGHT_USE_IIC_DRIVER",
                type: "bool",
                range: null,
                title: "使能IIC驱动",
                default: "n",
                children: [],
                depends_on: null,
                is_menuconfig: true,
              },
              {
                id: "CL_LIGHT_IIC_DRIVER_SDA",
                help: null,
                name: "CL_LIGHT_IIC_DRIVER_SDA",
                type: "int",
                range: null,
                title: "SDA引脚",
                children: [],
                depends_on: "CL_LIGHT_USE_IIC_DRIVER",
              },
              {
                id: "CL_LIGHT_IIC_DRIVER_SCL",
                help: null,
                name: "CL_LIGHT_IIC_DRIVER_SCL",
                type: "int",
                range: null,
                title: "SCL引脚",
                children: [],
                depends_on: "CL_LIGHT_USE_IIC_DRIVER",
              },
            ],
            depends_on: null,
            is_menuconfig: true,
          },
          {
            id: "产品配置-rgbcw-r-配置",
            type: "menu",
            title: "R 配置",
            children: [
              {
                id: "产品配置-rgbcw-r-配置-r-驱动方式",
                help: null,
                name: "CL_LIGHT_R_DRIVER_TYPE",
                type: "choice",
                title: "R 驱动方式",
                children: [
                  {
                    id: "CL_LIGHT_R_DRIVER_TYPE_PWM",
                    help: null,
                    name: "CL_LIGHT_R_DRIVER_TYPE_PWM",
                    type: "bool",
                    range: null,
                    title: "PWM",
                    default: "y",
                    children: [],
                    depends_on:
                      "CL_LIGHT_USE_PWM_DRIVER && <choice CL_LIGHT_R_DRIVER_TYPE>",
                  },
                  {
                    id: "CL_LIGHT_R_DRIVER_TYPE_IIC_BP5758D",
                    help: null,
                    name: "CL_LIGHT_R_DRIVER_TYPE_IIC_BP5758D",
                    type: "bool",
                    range: null,
                    title: "IIC_BP5758D",
                    children: [],
                    depends_on:
                      "CL_LIGHT_USE_IIC_DRIVER && <choice CL_LIGHT_R_DRIVER_TYPE>",
                  },
                ],
                depends_on: "CL_LIGHT_RGB || CL_LIGHT_RGBC || CL_LIGHT_RGBCW",
              },
              {
                id: "CL_LIGHT_R_DRIVER_CHANNEL",
                help: null,
                name: "CL_LIGHT_R_DRIVER_CHANNEL",
                type: "int",
                range: null,
                title: "R 驱动信道",
                default: "1",
                children: [],
                depends_on:
                  "CL_LIGHT_USE_IIC_DRIVER && (CL_LIGHT_RGB || CL_LIGHT_RGBC || CL_LIGHT_RGBCW)",
              },
              {
                id: "CL_LIGHT_R_DRIVER_PWM_IO",
                help: null,
                name: "CL_LIGHT_R_DRIVER_PWM_IO",
                type: "int",
                range: [0, 36],
                title: "PWM引脚",
                default: "14",
                children: [],
                depends_on:
                  "CL_LIGHT_R_DRIVER_TYPE_PWM && (CL_LIGHT_RGB || CL_LIGHT_RGBC || CL_LIGHT_RGBCW)",
              },
              {
                id: "CL_LIGHT_R_DRIVER_MAX_CURRENT",
                help: null,
                name: "CL_LIGHT_R_DRIVER_MAX_CURRENT",
                type: "int",
                range: null,
                title: "驱动最大电流",
                default: "10",
                children: [],
                depends_on:
                  "CL_LIGHT_R_DRIVER_TYPE_IIC_BP5758D && (CL_LIGHT_RGB || CL_LIGHT_RGBC || CL_LIGHT_RGBCW)",
              },
            ],
            depends_on: "CL_LIGHT_RGB || CL_LIGHT_RGBC || CL_LIGHT_RGBCW",
          },
          {
            id: "产品配置-rgbcw-g-配置",
            type: "menu",
            title: "G 配置",
            children: [
              {
                id: "产品配置-rgbcw-g-配置-g-驱动方式",
                help: null,
                name: "CL_LIGHT_G_DRIVER_TYPE",
                type: "choice",
                title: "G 驱动方式",
                children: [
                  {
                    id: "CL_LIGHT_G_DRIVER_TYPE_PWM",
                    help: null,
                    name: "CL_LIGHT_G_DRIVER_TYPE_PWM",
                    type: "bool",
                    range: null,
                    title: "PWM",
                    default: "y",
                    children: [],
                    depends_on:
                      "CL_LIGHT_USE_PWM_DRIVER && <choice CL_LIGHT_G_DRIVER_TYPE>",
                  },
                  {
                    id: "CL_LIGHT_G_DRIVER_TYPE_IIC_BP5758D",
                    help: null,
                    name: "CL_LIGHT_G_DRIVER_TYPE_IIC_BP5758D",
                    type: "bool",
                    range: null,
                    title: "IIC_BP5758D",
                    children: [],
                    depends_on:
                      "CL_LIGHT_USE_IIC_DRIVER && <choice CL_LIGHT_G_DRIVER_TYPE>",
                  },
                ],
                depends_on: "CL_LIGHT_RGB || CL_LIGHT_RGBC || CL_LIGHT_RGBCW",
              },
              {
                id: "CL_LIGHT_G_DRIVER_CHANNEL",
                help: null,
                name: "CL_LIGHT_G_DRIVER_CHANNEL",
                type: "int",
                range: null,
                title: "G 驱动信道",
                default: "2",
                children: [],
                depends_on:
                  "CL_LIGHT_USE_IIC_DRIVER && (CL_LIGHT_RGB || CL_LIGHT_RGBC || CL_LIGHT_RGBCW)",
              },
              {
                id: "CL_LIGHT_G_DRIVER_PWM_IO",
                help: null,
                name: "CL_LIGHT_G_DRIVER_PWM_IO",
                type: "int",
                range: [0, 36],
                title: "PWM引脚",
                default: "20",
                children: [],
                depends_on:
                  "CL_LIGHT_G_DRIVER_TYPE_PWM && (CL_LIGHT_RGB || CL_LIGHT_RGBC || CL_LIGHT_RGBCW)",
              },
              {
                id: "CL_LIGHT_G_DRIVER_MAX_CURRENT",
                help: null,
                name: "CL_LIGHT_G_DRIVER_MAX_CURRENT",
                type: "int",
                range: null,
                title: "驱动最大电流",
                default: "10",
                children: [],
                depends_on:
                  "CL_LIGHT_G_DRIVER_TYPE_IIC_BP5758D && (CL_LIGHT_RGB || CL_LIGHT_RGBC || CL_LIGHT_RGBCW)",
              },
            ],
            depends_on: "CL_LIGHT_RGB || CL_LIGHT_RGBC || CL_LIGHT_RGBCW",
          },
          {
            id: "产品配置-rgbcw-b-配置",
            type: "menu",
            title: "B 配置",
            children: [
              {
                id: "产品配置-rgbcw-b-配置-b-驱动方式",
                help: null,
                name: "CL_LIGHT_B_DRIVER_TYPE",
                type: "choice",
                title: "B 驱动方式",
                children: [
                  {
                    id: "CL_LIGHT_B_DRIVER_TYPE_PWM",
                    help: null,
                    name: "CL_LIGHT_B_DRIVER_TYPE_PWM",
                    type: "bool",
                    range: null,
                    title: "PWM",
                    default: "y",
                    children: [],
                    depends_on:
                      "CL_LIGHT_USE_PWM_DRIVER && <choice CL_LIGHT_B_DRIVER_TYPE>",
                  },
                  {
                    id: "CL_LIGHT_B_DRIVER_TYPE_IIC_BP5758D",
                    help: null,
                    name: "CL_LIGHT_B_DRIVER_TYPE_IIC_BP5758D",
                    type: "bool",
                    range: null,
                    title: "IIC_BP5758D",
                    children: [],
                    depends_on:
                      "CL_LIGHT_USE_IIC_DRIVER && <choice CL_LIGHT_B_DRIVER_TYPE>",
                  },
                ],
                depends_on: "CL_LIGHT_RGB || CL_LIGHT_RGBC || CL_LIGHT_RGBCW",
              },
              {
                id: "CL_LIGHT_B_DRIVER_CHANNEL",
                help: null,
                name: "CL_LIGHT_B_DRIVER_CHANNEL",
                type: "int",
                range: null,
                title: "B 驱动信道",
                default: "3",
                children: [],
                depends_on:
                  "CL_LIGHT_USE_IIC_DRIVER && (CL_LIGHT_RGB || CL_LIGHT_RGBC || CL_LIGHT_RGBCW)",
              },
              {
                id: "CL_LIGHT_B_DRIVER_PWM_IO",
                help: null,
                name: "CL_LIGHT_B_DRIVER_PWM_IO",
                type: "int",
                range: [0, 36],
                title: "PWM引脚",
                default: "21",
                children: [],
                depends_on:
                  "CL_LIGHT_B_DRIVER_TYPE_PWM && (CL_LIGHT_RGB || CL_LIGHT_RGBC || CL_LIGHT_RGBCW)",
              },
              {
                id: "CL_LIGHT_B_DRIVER_MAX_CURRENT",
                help: null,
                name: "CL_LIGHT_B_DRIVER_MAX_CURRENT",
                type: "int",
                range: null,
                title: "驱动最大电流",
                default: "10",
                children: [],
                depends_on:
                  "CL_LIGHT_B_DRIVER_TYPE_IIC_BP5758D && (CL_LIGHT_RGB || CL_LIGHT_RGBC || CL_LIGHT_RGBCW)",
              },
            ],
            depends_on: "CL_LIGHT_RGB || CL_LIGHT_RGBC || CL_LIGHT_RGBCW",
          },
          {
            id: "产品配置-rgbcw-c-cc-配置",
            type: "menu",
            title: "C(CC) 配置",
            children: [
              {
                id: "产品配置-rgbcw-c-cc-配置-c-驱动方式",
                help: null,
                name: "CL_LIGHT_C_DRIVER_TYPE",
                type: "choice",
                title: "C 驱动方式",
                children: [
                  {
                    id: "CL_LIGHT_C_DRIVER_TYPE_PWM",
                    help: null,
                    name: "CL_LIGHT_C_DRIVER_TYPE_PWM",
                    type: "bool",
                    range: null,
                    title: "PWM",
                    default: "y",
                    children: [],
                    depends_on:
                      "CL_LIGHT_USE_PWM_DRIVER && <choice CL_LIGHT_C_DRIVER_TYPE>",
                  },
                  {
                    id: "CL_LIGHT_C_DRIVER_TYPE_IIC_BP5758D",
                    help: null,
                    name: "CL_LIGHT_C_DRIVER_TYPE_IIC_BP5758D",
                    type: "bool",
                    range: null,
                    title: "IIC_BP5758D",
                    children: [],
                    depends_on:
                      "CL_LIGHT_USE_IIC_DRIVER && <choice CL_LIGHT_C_DRIVER_TYPE>",
                  },
                ],
                depends_on:
                  "CL_LIGHT_C || CL_LIGHT_CW || CL_LIGHT_RGBC || CL_LIGHT_RGBCW",
              },
              {
                id: "CL_LIGHT_C_DRIVER_CHANNEL",
                help: null,
                name: "CL_LIGHT_C_DRIVER_CHANNEL",
                type: "int",
                range: null,
                title: "C 驱动信道",
                default: "4",
                children: [],
                depends_on:
                  "CL_LIGHT_USE_IIC_DRIVER && (CL_LIGHT_C || CL_LIGHT_CW || CL_LIGHT_RGBC || CL_LIGHT_RGBCW)",
              },
              {
                id: "CL_LIGHT_C_DRIVER_PWM_IO",
                help: null,
                name: "CL_LIGHT_C_DRIVER_PWM_IO",
                type: "int",
                range: [0, 36],
                title: "PWM引脚",
                default: "22",
                children: [],
                depends_on:
                  "CL_LIGHT_C_DRIVER_TYPE_PWM && (CL_LIGHT_C || CL_LIGHT_CW || CL_LIGHT_RGBC || CL_LIGHT_RGBCW)",
              },
              {
                id: "CL_LIGHT_C_DRIVER_MAX_CURRENT",
                help: null,
                name: "CL_LIGHT_C_DRIVER_MAX_CURRENT",
                type: "int",
                range: null,
                title: "驱动最大电流",
                default: "10",
                children: [],
                depends_on:
                  "CL_LIGHT_C_DRIVER_TYPE_IIC_BP5758D && (CL_LIGHT_C || CL_LIGHT_CW || CL_LIGHT_RGBC || CL_LIGHT_RGBCW)",
              },
            ],
            depends_on:
              "CL_LIGHT_C || CL_LIGHT_CW || CL_LIGHT_RGBC || CL_LIGHT_RGBCW",
          },
          {
            id: "产品配置-rgbcw-w-t-配置",
            type: "menu",
            title: "W(T) 配置",
            children: [
              {
                id: "产品配置-rgbcw-w-t-配置-w-驱动方式",
                help: null,
                name: "CL_LIGHT_W_DRIVER_TYPE",
                type: "choice",
                title: "W 驱动方式",
                children: [
                  {
                    id: "CL_LIGHT_W_DRIVER_TYPE_PWM",
                    help: null,
                    name: "CL_LIGHT_W_DRIVER_TYPE_PWM",
                    type: "bool",
                    range: null,
                    title: "PWM",
                    default: "y",
                    children: [],
                    depends_on:
                      "CL_LIGHT_USE_PWM_DRIVER && <choice CL_LIGHT_W_DRIVER_TYPE>",
                  },
                  {
                    id: "CL_LIGHT_W_DRIVER_TYPE_IIC_BP5758D",
                    help: null,
                    name: "CL_LIGHT_W_DRIVER_TYPE_IIC_BP5758D",
                    type: "bool",
                    range: null,
                    title: "IIC_BP5758D",
                    children: [],
                    depends_on:
                      "CL_LIGHT_USE_IIC_DRIVER && <choice CL_LIGHT_W_DRIVER_TYPE>",
                  },
                ],
                depends_on: "CL_LIGHT_CW || CL_LIGHT_RGBCW",
              },
              {
                id: "CL_LIGHT_W_DRIVER_CHANNEL",
                help: null,
                name: "CL_LIGHT_W_DRIVER_CHANNEL",
                type: "int",
                range: null,
                title: "W 驱动信道",
                default: "5",
                children: [],
                depends_on:
                  "CL_LIGHT_USE_IIC_DRIVER && (CL_LIGHT_CW || CL_LIGHT_RGBCW)",
              },
              {
                id: "CL_LIGHT_W_DRIVER_PWM_IO",
                help: null,
                name: "CL_LIGHT_W_DRIVER_PWM_IO",
                type: "int",
                range: [0, 36],
                title: "PWM引脚",
                default: "3",
                children: [],
                depends_on:
                  "CL_LIGHT_W_DRIVER_TYPE_PWM && (CL_LIGHT_CW || CL_LIGHT_RGBCW)",
              },
              {
                id: "CL_LIGHT_W_DRIVER_MAX_CURRENT",
                help: null,
                name: "CL_LIGHT_W_DRIVER_MAX_CURRENT",
                type: "int",
                range: null,
                title: "驱动最大电流",
                default: "10",
                children: [],
                depends_on:
                  "CL_LIGHT_W_DRIVER_TYPE_IIC_BP5758D && (CL_LIGHT_CW || CL_LIGHT_RGBCW)",
              },
            ],
            depends_on: "CL_LIGHT_CW || CL_LIGHT_RGBCW",
          },
          {
            id: "产品配置-rgbcw-参数配置",
            type: "menu",
            title: "参数配置",
            children: [
              {
                id: "产品配置-rgbcw-参数配置-色温输出方式",
                help: null,
                name: "CL_LIGHT_CW_OUT_TYPE",
                type: "choice",
                title: "色温输出方式",
                children: [
                  {
                    id: "CL_LIGHT_CW_OUT_TYPE_FULLPOWER",
                    help: null,
                    name: "CL_LIGHT_CW_OUT_TYPE_FULLPOWER",
                    type: "bool",
                    range: null,
                    title: "全功率(倍功率)",
                    children: [],
                    depends_on: "<choice CL_LIGHT_CW_OUT_TYPE>",
                  },
                  {
                    id: "CL_LIGHT_CW_OUT_TYPE_HALFPOWER",
                    help: null,
                    name: "CL_LIGHT_CW_OUT_TYPE_HALFPOWER",
                    type: "bool",
                    range: null,
                    title: "半功率(恒功率)",
                    children: [],
                    depends_on: "<choice CL_LIGHT_CW_OUT_TYPE>",
                  },
                  {
                    id: "CL_LIGHT_CW_OUT_TYPE_CW2RGB",
                    help: null,
                    name: "CL_LIGHT_CW_OUT_TYPE_CW2RGB",
                    type: "bool",
                    range: null,
                    title: "RGB混色",
                    default: "y",
                    children: [],
                    depends_on: "<choice CL_LIGHT_CW_OUT_TYPE>",
                  },
                  {
                    id: "CL_LIGHT_CW_OUT_TYPE_CCT",
                    help: null,
                    name: "CL_LIGHT_CW_OUT_TYPE_CCT",
                    type: "bool",
                    range: null,
                    title: "CCT",
                    children: [],
                    depends_on: "<choice CL_LIGHT_CW_OUT_TYPE>",
                  },
                  {
                    id: "CL_LIGHT_CW_OUT_TYPE_CWL",
                    help: null,
                    name: "CL_LIGHT_CW_OUT_TYPE_CWL",
                    type: "bool",
                    range: null,
                    title: "CWL",
                    children: [],
                    depends_on: "<choice CL_LIGHT_CW_OUT_TYPE>",
                  },
                  {
                    id: "CL_LIGHT_CW_OUT_TYPE_C2RGB",
                    help: null,
                    name: "CL_LIGHT_CW_OUT_TYPE_C2RGB",
                    type: "bool",
                    range: null,
                    title: "C2RGB",
                    children: [],
                    depends_on: "<choice CL_LIGHT_CW_OUT_TYPE>",
                  },
                ],
                depends_on:
                  "CL_LIGHT_CW || CL_LIGHT_RGB || CL_LIGHT_RGBC || CL_LIGHT_RGBCW",
              },
              {
                id: "CL_LIGHT_CCT_WHITE_PWM",
                help: null,
                name: "CL_LIGHT_CCT_WHITE_PWM",
                type: "int",
                range: null,
                title: "白光对应的PWM",
                default: "0",
                children: [],
                depends_on: "CL_LIGHT_CW_OUT_TYPE_CCT",
              },
              {
                id: "产品配置-rgbcw-参数配置-颜色过度方式",
                help: null,
                name: "CL_LIGHT_TRANSITION_TYPE",
                type: "choice",
                title: "颜色过度方式",
                children: [
                  {
                    id: "CL_LIGHT_TRANSITION_TYPE_JUMP",
                    help: null,
                    name: "CL_LIGHT_TRANSITION_TYPE_JUMP",
                    type: "bool",
                    range: null,
                    title: "跳变",
                    children: [],
                    depends_on: "<choice CL_LIGHT_TRANSITION_TYPE>",
                  },
                  {
                    id: "CL_LIGHT_TRANSITION_TYPE_SHADE",
                    help: null,
                    name: "CL_LIGHT_TRANSITION_TYPE_SHADE",
                    type: "bool",
                    range: null,
                    title: "渐变",
                    default: "y",
                    children: [],
                    depends_on: "<choice CL_LIGHT_TRANSITION_TYPE>",
                  },
                ],
                depends_on: null,
              },
              {
                id: "CL_LIGHT_CW_MIN_BRIGHT",
                help: null,
                name: "CL_LIGHT_CW_MIN_BRIGHT",
                type: "int",
                range: [1, 1000],
                title: "CW最小亮度",
                default: "100",
                children: [],
                depends_on: null,
              },
              {
                id: "CL_LIGHT_CW_MAX_BRIGHT",
                help: null,
                name: "CL_LIGHT_CW_MAX_BRIGHT",
                type: "int",
                range: [1, 1000],
                title: "CW最大亮度",
                default: "1000",
                children: [],
                depends_on: null,
              },
              {
                id: "CL_LIGHT_RGB_MIN_BRIGHT",
                help: null,
                name: "CL_LIGHT_RGB_MIN_BRIGHT",
                type: "int",
                range: [1, 1000],
                title: "RGB最小亮度",
                default: "100",
                children: [],
                depends_on: null,
              },
              {
                id: "CL_LIGHT_RGB_MAX_BRIGHT",
                help: null,
                name: "CL_LIGHT_RGB_MAX_BRIGHT",
                type: "int",
                range: [1, 1000],
                title: "RGB最大亮度",
                default: "1000",
                children: [],
                depends_on: null,
              },
              {
                id: "CL_LIGHT_GENERAL_COLOR_CAL",
                help: null,
                name: "CL_LIGHT_GENERAL_COLOR_CAL",
                type: "bool",
                range: null,
                title: "通用颜色矫正",
                default: "y",
                children: [],
                depends_on: null,
              },
              {
                id: "CL_LIGHT_RGB_POWER_LIMIT",
                help: null,
                name: "CL_LIGHT_RGB_POWER_LIMIT",
                type: "bool",
                range: null,
                title: "RGB功率限制",
                default: "n",
                children: [],
                depends_on: null,
              },
              {
                id: "CL_LIGHT_CW_POWER_LIMIT",
                help: null,
                name: "CL_LIGHT_CW_POWER_LIMIT",
                type: "bool",
                range: null,
                title: "CW功率限制",
                default: "n",
                children: [],
                depends_on: null,
              },
            ],
            depends_on: null,
          },
        ],
        depends_on: null,
      },
      {
        id: "产品配置-默认状态设置",
        type: "menu",
        title: "默认状态设置",
        children: [
          {
            id: "CL_LIGHT_FIRST_WIFI_CFG_STATUS",
            help: null,
            name: "CL_LIGHT_FIRST_WIFI_CFG_STATUS",
            type: "bool",
            range: null,
            title: "首次配网开启配网状态提醒",
            default: "y",
            children: [],
            depends_on: null,
          },
          {
            id: "CL_LIGHT_DEFAULT_COLOR_H",
            help: null,
            name: "CL_LIGHT_DEFAULT_COLOR_H",
            type: "int",
            range: null,
            title: "默认色值(H)",
            default: "0",
            children: [],
            depends_on: null,
          },
          {
            id: "CL_LIGHT_DEFAULT_COLOR_S",
            help: null,
            name: "CL_LIGHT_DEFAULT_COLOR_S",
            type: "int",
            range: null,
            title: "默认饱和度(S)",
            default: "1000",
            children: [],
            depends_on: null,
          },
          {
            id: "CL_LIGHT_DEFAULT_COLOR_T",
            help: null,
            name: "CL_LIGHT_DEFAULT_COLOR_T",
            type: "int",
            range: null,
            title: "默认色温(T)",
            default: "65535",
            children: [],
            depends_on: null,
          },
          {
            id: "CL_LIGHT_DEFAULT_BRIGHT",
            help: null,
            name: "CL_LIGHT_DEFAULT_BRIGHT",
            type: "int",
            range: [0, 1000],
            title: "默认亮度",
            default: "1000",
            children: [],
            depends_on: null,
          },
          {
            id: "CL_LIGHT_DEFAULT_SPEED",
            help: null,
            name: "CL_LIGHT_DEFAULT_SPEED",
            type: "int",
            range: [0, 1000],
            title: "默认速度",
            default: "500",
            children: [],
            depends_on: null,
          },
          {
            id: "产品配置-默认状态设置-渐变时间设置",
            type: "menu",
            title: "渐变时间设置",
            children: [
              {
                id: "CL_LIGHT_STATIC_SHADE_TIME",
                help: null,
                name: "CL_LIGHT_STATIC_SHADE_TIME",
                type: "int",
                range: [100, 5000],
                title: "颜色切换渐变时间",
                default: "250",
                children: [],
                depends_on: null,
              },
              {
                id: "CL_LIGHT_ON_SHADE_TIME",
                help: null,
                name: "CL_LIGHT_ON_SHADE_TIME",
                type: "int",
                range: [100, 5000],
                title: "开灯渐变时间",
                default: "200",
                children: [],
                depends_on: null,
              },
              {
                id: "CL_LIGHT_OFF_SHADE_TIME",
                help: null,
                name: "CL_LIGHT_OFF_SHADE_TIME",
                type: "int",
                range: [100, 5000],
                title: "关灯渐变时间",
                default: "100",
                children: [],
                depends_on: null,
              },
            ],
            depends_on: null,
          },
        ],
        depends_on: null,
      },
      {
        id: "CL_POWER_SWITCH_CONFIG",
        help: null,
        name: "CL_POWER_SWITCH_CONFIG",
        type: "menu",
        range: null,
        title: "多次上电配网",
        default: "y",
        children: [
          {
            id: "CL_POWER_SWITCH_CONFIG",
            help: null,
            name: "CL_POWER_SWITCH_CONFIG",
            type: "bool",
            range: null,
            title: "多次上电配网",
            default: "y",
            children: [],
            depends_on: null,
            is_menuconfig: true,
          },
          {
            id: "CL_POWER_SWITCH_CONFIG_COUNT",
            help: null,
            name: "CL_POWER_SWITCH_CONFIG_COUNT",
            type: "int",
            range: [0, 30],
            title: "重复上电次数",
            default: "3",
            children: [],
            depends_on: "CL_POWER_SWITCH_CONFIG",
          },
          {
            id: "CL_POWER_SWITCH_CONFIG_CLEAN_TIME",
            help: null,
            name: "CL_POWER_SWITCH_CONFIG_CLEAN_TIME",
            type: "int",
            range: [0, 60000],
            title: "清除时间",
            default: "5000",
            children: [],
            depends_on: "CL_POWER_SWITCH_CONFIG",
          },
        ],
        depends_on: null,
        is_menuconfig: true,
      },
      {
        id: "CL_MUSIC_MODE",
        help: null,
        name: "CL_MUSIC_MODE",
        type: "menu",
        range: null,
        title: "音乐模式",
        default: "y",
        children: [
          {
            id: "CL_MUSIC_MODE",
            help: null,
            name: "CL_MUSIC_MODE",
            type: "bool",
            range: null,
            title: "音乐模式",
            default: "y",
            children: [],
            depends_on: null,
            is_menuconfig: true,
          },
          {
            id: "CL_MUSIC_MODE_OUT",
            help: null,
            name: "CL_MUSIC_MODE_OUT",
            type: "bool",
            range: null,
            title: "设备麦音乐模式",
            default: "n",
            children: [
              {
                id: "CL_MUSIC_MODE_OUT_ADC_PIN",
                help: null,
                name: "CL_MUSIC_MODE_OUT_ADC_PIN",
                type: "int",
                range: null,
                title: "ADC引脚",
                default: "5",
                children: [],
                depends_on: "CL_MUSIC_MODE && CL_MUSIC_MODE_OUT",
              },
            ],
            depends_on: "CL_MUSIC_MODE",
          },
          {
            id: "CL_MUSIC_MODE_INT",
            help: null,
            name: "CL_MUSIC_MODE_INT",
            type: "bool",
            range: null,
            title: "手机麦音乐模式",
            default: "y",
            children: [],
            depends_on: "CL_MUSIC_MODE",
          },
          {
            id: "CL_MUSIC_MODE_SENSITIVITY",
            help: null,
            name: "CL_MUSIC_MODE_SENSITIVITY",
            type: "int",
            range: [0, 100],
            title: "默认灵敏度",
            default: "60",
            children: [],
            depends_on: "CL_MUSIC_MODE",
          },
          {
            id: "CL_MUSIC_MODE_INDEX",
            help: null,
            name: "CL_MUSIC_MODE_INDEX",
            type: "int",
            range: [0, 255],
            title: "默认音乐效果",
            default: "0",
            children: [],
            depends_on: "CL_MUSIC_MODE",
          },
        ],
        depends_on: null,
        is_menuconfig: true,
      },
      {
        id: "CL_REMOTE_CONTROL",
        help: null,
        name: "CL_REMOTE_CONTROL",
        type: "menu",
        range: null,
        title: "遥控控制",
        default: "n",
        children: [
          {
            id: "CL_REMOTE_CONTROL",
            help: null,
            name: "CL_REMOTE_CONTROL",
            type: "bool",
            range: null,
            title: "遥控控制",
            default: "n",
            children: [],
            depends_on: null,
            is_menuconfig: true,
          },
          {
            id: "产品配置-遥控控制-遥控控制方式",
            help: null,
            name: "CL_REMOTE_CONTROL_TYPE",
            type: "choice",
            title: "遥控控制方式",
            children: [
              {
                id: "CL_REMOTE_CONTROL_TYPE_IR",
                help: null,
                name: "CL_REMOTE_CONTROL_TYPE_IR",
                type: "bool",
                range: null,
                title: "红外",
                default: "y",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_TYPE>",
              },
              {
                id: "CL_REMOTE_CONTROL_TYPE_RF",
                help: null,
                name: "CL_REMOTE_CONTROL_TYPE_RF",
                type: "bool",
                range: null,
                title: "433",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_TYPE>",
              },
              {
                id: "CL_REMOTE_CONTROL_TYPE_BLE",
                help: null,
                name: "CL_REMOTE_CONTROL_TYPE_BLE",
                type: "bool",
                range: null,
                title: "蓝牙2.4G",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_TYPE>",
              },
              {
                id: "CL_REMOTE_CONTROL_TYPE_COZYLIFE_OTP",
                help: null,
                name: "CL_REMOTE_CONTROL_TYPE_COZYLIFE_OTP",
                type: "bool",
                range: null,
                title: "CozyLife OTP",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_TYPE>",
              },
              {
                id: "CL_REMOTE_CONTROL_TYPE_USER_DEFINE",
                help: null,
                name: "CL_REMOTE_CONTROL_TYPE_USER_DEFINE",
                type: "bool",
                range: null,
                title: "宏定义",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_TYPE>",
              },
            ],
            depends_on: "CL_REMOTE_CONTROL",
          },
          {
            id: "CL_IR_CONTROL_PIN",
            help: null,
            name: "CL_IR_CONTROL_PIN",
            type: "int",
            range: null,
            title: "红外驱动引脚",
            children: [],
            depends_on: "CL_REMOTE_CONTROL && CL_REMOTE_CONTROL_TYPE_IR",
          },
          {
            id: "CL_REMOTE_CONTROL_IR_HEAD",
            help: null,
            name: "CL_REMOTE_CONTROL_IR_HEAD",
            type: "int",
            range: null,
            title: "红外码头",
            children: [],
            depends_on: "CL_REMOTE_CONTROL && CL_REMOTE_CONTROL_TYPE_IR",
          },
        ],
        depends_on: null,
        is_menuconfig: true,
      },
      {
        id: "产品配置--type-menu2-",
        type: "menu2",
        title: "",
        children: [
          {
            id: "CL_REMOTE_CONTROL_-id-_CODE",
            help: null,
            name: "CL_REMOTE_CONTROL_-id-_CODE",
            type: "int",
            range: null,
            title: "Code",
            default: "0",
            children: [],
            placement: "left",
            depends_on: "CL_REMOTE_CONTROL",
          },
          {
            id: "产品配置--type-menu2--fun-placement-middle-",
            help: null,
            name: "CL_REMOTE_CONTROL_-id-_FUN",
            type: "choice",
            title: "Fun",
            children: [
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_light_on",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_light_on",
                type: "bool",
                range: null,
                title: "on",
                default: "y",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_light_off",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_light_off",
                type: "bool",
                range: null,
                title: "off",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_color",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_color",
                type: "bool",
                range: null,
                title: "color",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_remote_lock_and_unlock",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_remote_lock_and_unlock",
                type: "bool",
                range: null,
                title: "lock",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_auto_scene_mode",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_auto_scene_mode",
                type: "bool",
                range: null,
                title: "auto",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_music_mode",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_music_mode",
                type: "bool",
                range: null,
                title: "音乐模式",
                children: [],
                depends_on:
                  "CL_MUSIC_MODE && <choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_countdown",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_countdown",
                type: "bool",
                range: null,
                title: "倒计时",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_speed",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_speed",
                type: "bool",
                range: null,
                title: "速度+",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_speed",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_speed",
                type: "bool",
                range: null,
                title: "速度-",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_temp",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_temp",
                type: "bool",
                range: null,
                title: "色温+",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_temp",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_temp",
                type: "bool",
                range: null,
                title: "色温-",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_bright",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_bright",
                type: "bool",
                range: null,
                title: "亮度+",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_bright",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_bright",
                type: "bool",
                range: null,
                title: "亮度-",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_scene_mode",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_scene_mode",
                type: "bool",
                range: null,
                title: "场景+",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_scene_mode",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_scene_mode",
                type: "bool",
                range: null,
                title: "场景-",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_rgb_index",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_rgb_index",
                type: "bool",
                range: null,
                title: "三色循环",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_rgb_index1",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_rgb_index1",
                type: "bool",
                range: null,
                title: "七色循环",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_cw",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_cw",
                type: "bool",
                range: null,
                title: "冷暖切换",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_custom",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_custom",
                type: "bool",
                range: null,
                title: "custom",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
            ],
            placement: "middle",
            depends_on: "CL_REMOTE_CONTROL",
          },
          {
            id: "CL_REMOTE_CONTROL_-id-_FUN_arg",
            help: null,
            name: "CL_REMOTE_CONTROL_-id-_FUN_arg",
            type: "string",
            range: null,
            title: "",
            default: '""',
            children: [],
            placement: "right",
            depends_on:
              "(CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_countdown || CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_color || CL_REMOTE_CONTROL_-id-_FUN_custom || CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_music_mode) && CL_REMOTE_CONTROL",
          },
        ],
        depends_on: "CL_REMOTE_CONTROL",
      },
      {
        id: "CL_KEY_CONTROL",
        help: null,
        name: "CL_KEY_CONTROL",
        type: "menu",
        range: null,
        title: "按键控制",
        default: "n",
        children: [
          {
            id: "CL_KEY_CONTROL",
            help: null,
            name: "CL_KEY_CONTROL",
            type: "bool",
            range: null,
            title: "按键控制",
            default: "n",
            children: [],
            depends_on: null,
            is_menuconfig: true,
          },
        ],
        depends_on: null,
        is_menuconfig: true,
      },
      {
        id: "产品配置--type-menu2-",
        type: "menu2",
        title: "",
        children: [
          {
            id: "CL_KEY_CONTROL_-id-_CODE",
            help: null,
            name: "CL_KEY_CONTROL_-id-_CODE",
            type: "int",
            range: null,
            title: "引脚",
            children: [],
            placement: "left",
            depends_on: "CL_KEY_CONTROL",
          },
          {
            id: "产品配置--type-menu2--单击-placement-right-",
            help: null,
            name: "CL_KEY_CONTROL_-id-_CLICK_FUN",
            type: "choice",
            title: "单击",
            children: [
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_null",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_null",
                type: "bool",
                range: null,
                title: "不设置",
                default: "y",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_light_on",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_light_on",
                type: "bool",
                range: null,
                title: "on",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_light_off",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_light_off",
                type: "bool",
                range: null,
                title: "off",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
            ],
            placement: "right",
            depends_on: "CL_KEY_CONTROL",
          },
          {
            id: "产品配置--type-menu2--双击-placement-right-",
            help: null,
            name: "CL_KEY_CONTROL_-id-_DOUBLE_FUN",
            type: "choice",
            title: "双击",
            children: [
              {
                id: "CL_KEY_CONTROL_-id-_DOUBLE_FUN_fun_null",
                help: null,
                name: "CL_KEY_CONTROL_-id-_DOUBLE_FUN_fun_null",
                type: "bool",
                range: null,
                title: "不设置",
                default: "y",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_DOUBLE_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_DOUBLE_FUN_fun_btn_remote_fun_light_on",
                help: null,
                name: "CL_KEY_CONTROL_-id-_DOUBLE_FUN_fun_btn_remote_fun_light_on",
                type: "bool",
                range: null,
                title: "on",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_DOUBLE_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_DOUBLE_FUN_fun_btn_remote_fun_light_off",
                help: null,
                name: "CL_KEY_CONTROL_-id-_DOUBLE_FUN_fun_btn_remote_fun_light_off",
                type: "bool",
                range: null,
                title: "off",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_DOUBLE_FUN>",
              },
            ],
            placement: "right",
            depends_on: "CL_KEY_CONTROL",
          },
          {
            id: "产品配置--type-menu2--长按-placement-right-",
            help: null,
            name: "CL_KEY_CONTROL_-id-_LONG_FUN",
            type: "choice",
            title: "长按",
            children: [
              {
                id: "CL_KEY_CONTROL_-id-_LONG_FUN_null",
                help: null,
                name: "CL_KEY_CONTROL_-id-_LONG_FUN_null",
                type: "bool",
                range: null,
                title: "不设置",
                default: "y",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_LONG_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_LONG_FUN_fun_btn_remote_fun_light_on",
                help: null,
                name: "CL_KEY_CONTROL_-id-_LONG_FUN_fun_btn_remote_fun_light_on",
                type: "bool",
                range: null,
                title: "on",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_LONG_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_LONG_FUN_fun_btn_remote_fun_light_off",
                help: null,
                name: "CL_KEY_CONTROL_-id-_LONG_FUN_fun_btn_remote_fun_light_off",
                type: "bool",
                range: null,
                title: "off",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_LONG_FUN>",
              },
            ],
            placement: "right",
            depends_on: "CL_KEY_CONTROL",
          },
        ],
        depends_on: "CL_KEY_CONTROL",
      },
    ],
    depends_on: null,
  },
];
