export const kconfigJSON = [
  {
    id: "基本信息",
    type: "menu",
    title: "基本信息",
    children: [
      {
        id: "CL_PRODUCT_NAME",
        help: null,
        name: "CL_PRODUCT_NAME",
        type: "string",
        range: null,
        title: "产品名称",
        default: '""',
        children: [],
        depends_on: null,
      },
      {
        id: "CL_HARDWARE_VERSION",
        help: null,
        name: "CL_HARDWARE_VERSION",
        type: "string",
        range: null,
        title: "硬件版本",
        default: '"1.0.0"',
        children: [],
        depends_on: null,
      },
    ],
    depends_on: null,
  },
  {
    id: "芯片模组",
    type: "menu",
    title: "芯片模组",
    children: [
      {
        id: "芯片模组-芯片",
        help: null,
        name: "CL_CHIP_TYPE",
        type: "choice",
        title: "芯片",
        children: [
          {
            id: "CL_CHIP_TYPE_NULL",
            help: null,
            name: "CL_CHIP_TYPE_NULL",
            type: "bool",
            range: null,
            title: "未设置",
            default: "y",
            children: [],
            depends_on: "<choice CL_CHIP_TYPE>",
          },
          {
            id: "CL_CHIP_TYPE_ESP32",
            help: null,
            name: "CL_CHIP_TYPE_ESP32",
            type: "bool",
            range: null,
            title: "ESP32",
            children: [],
            depends_on: "<choice CL_CHIP_TYPE>",
          },
          {
            id: "CL_CHIP_TYPE_ESP32C3",
            help: null,
            name: "CL_CHIP_TYPE_ESP32C3",
            type: "bool",
            range: null,
            title: "ESP32C3",
            children: [],
            depends_on: "<choice CL_CHIP_TYPE>",
          },
          {
            id: "CL_CHIP_TYPE_ESP8685",
            help: null,
            name: "CL_CHIP_TYPE_ESP8685",
            type: "bool",
            range: null,
            title: "ESP8685",
            children: [],
            depends_on: "<choice CL_CHIP_TYPE>",
          },
          {
            id: "CL_CHIP_TYPE_ESP8684",
            help: null,
            name: "CL_CHIP_TYPE_ESP8684",
            type: "bool",
            range: null,
            title: "ESP8684",
            children: [],
            depends_on: "<choice CL_CHIP_TYPE>",
          },
          {
            id: "CL_CHIP_TYPE_BL602C",
            help: null,
            name: "CL_CHIP_TYPE_BL602C",
            type: "bool",
            range: null,
            title: "BL602C",
            children: [],
            depends_on: "<choice CL_CHIP_TYPE>",
          },
          {
            id: "CL_CHIP_TYPE_BL602L",
            help: null,
            name: "CL_CHIP_TYPE_BL602L",
            type: "bool",
            range: null,
            title: "BL602L",
            children: [],
            depends_on: "<choice CL_CHIP_TYPE>",
          },
          {
            id: "CL_CHIP_TYPE_LN882H",
            help: null,
            name: "CL_CHIP_TYPE_LN882H",
            type: "bool",
            range: null,
            title: "LN882H",
            children: [],
            depends_on: "<choice CL_CHIP_TYPE>",
          },
        ],
        depends_on: null,
      },
      {
        id: "芯片模组-esp32模组",
        help: null,
        name: "CL_ESP32_MODULE",
        type: "choice",
        title: "ESP32模组",
        children: [
          {
            id: "CL_ESP32_MODULE_NULL",
            help: null,
            name: "CL_ESP32_MODULE_NULL",
            type: "bool",
            range: null,
            title: "不使用模组",
            default: "y",
            children: [],
            depends_on: "<choice CL_ESP32_MODULE>",
          },
          {
            id: "CL_ESP32_MODULE_ESP_HOME",
            help: null,
            name: "CL_ESP32_MODULE_ESP_HOME",
            type: "bool",
            range: null,
            title: "ESP-HOME",
            children: [],
            depends_on: "<choice CL_ESP32_MODULE>",
          },
          {
            id: "CL_ESP32_MODULE_ESP_02",
            help: null,
            name: "CL_ESP32_MODULE_ESP_02",
            type: "bool",
            range: null,
            title: "ESP-02",
            children: [],
            depends_on: "<choice CL_ESP32_MODULE>",
          },
        ],
        depends_on: "CL_CHIP_TYPE_ESP32",
      },
      {
        id: "芯片模组-esp32c3模组",
        help: null,
        name: "CL_ESP32C3_MODULE",
        type: "choice",
        title: "ESP32C3模组",
        children: [
          {
            id: "CL_ESP32C3_MODULE_NULL",
            help: null,
            name: "CL_ESP32C3_MODULE_NULL",
            type: "bool",
            range: null,
            title: "不使用模组",
            default: "y",
            children: [],
            depends_on: "<choice CL_ESP32C3_MODULE>",
          },
          {
            id: "CL_ESP32C3_MODULE_ESP_C02",
            help: null,
            name: "CL_ESP32C3_MODULE_ESP_C02",
            type: "bool",
            range: null,
            title: "ESP-C02",
            children: [],
            depends_on: "<choice CL_ESP32C3_MODULE>",
          },
          {
            id: "CL_ESP32C3_MODULE_ESP_C05",
            help: null,
            name: "CL_ESP32C3_MODULE_ESP_C05",
            type: "bool",
            range: null,
            title: "ESP-C05",
            children: [],
            depends_on: "<choice CL_ESP32C3_MODULE>",
          },
          {
            id: "CL_ESP32C3_MODULE_ESP_C12",
            help: null,
            name: "CL_ESP32C3_MODULE_ESP_C12",
            type: "bool",
            range: null,
            title: "ESP-C12",
            children: [],
            depends_on: "<choice CL_ESP32C3_MODULE>",
          },
        ],
        depends_on: "CL_CHIP_TYPE_ESP32C3",
      },
      {
        id: "芯片模组-esp8685模组",
        help: null,
        name: "CL_ESP8685_MODULE",
        type: "choice",
        title: "ESP8685模组",
        children: [
          {
            id: "CL_ESP8685_MODULE_NULL",
            help: null,
            name: "CL_ESP8685_MODULE_NULL",
            type: "bool",
            range: null,
            title: "不使用模组",
            default: "y",
            children: [],
            depends_on: "<choice CL_ESP8685_MODULE>",
          },
          {
            id: "CL_ESP8685_MODULE_ESP_C02M",
            help: null,
            name: "CL_ESP8685_MODULE_ESP_C02M",
            type: "bool",
            range: null,
            title: "ESP-C02M",
            children: [],
            depends_on: "<choice CL_ESP8685_MODULE>",
          },
          {
            id: "CL_ESP8685_MODULE_ESP_C05M",
            help: null,
            name: "CL_ESP8685_MODULE_ESP_C05M",
            type: "bool",
            range: null,
            title: "ESP-C05M",
            children: [],
            depends_on: "<choice CL_ESP8685_MODULE>",
          },
          {
            id: "CL_ESP8685_MODULE_ESP_C12M",
            help: null,
            name: "CL_ESP8685_MODULE_ESP_C12M",
            type: "bool",
            range: null,
            title: "ESP-C12M",
            children: [],
            depends_on: "<choice CL_ESP8685_MODULE>",
          },
        ],
        depends_on: "CL_CHIP_TYPE_ESP8685",
      },
      {
        id: "芯片模组-esp8684模组",
        help: null,
        name: "CL_ESP8684_MODULE",
        type: "choice",
        title: "ESP8684模组",
        children: [
          {
            id: "CL_ESP8684_MODULE_NULL",
            help: null,
            name: "CL_ESP8684_MODULE_NULL",
            type: "bool",
            range: null,
            title: "不使用模组",
            default: "y",
            children: [],
            depends_on: "<choice CL_ESP8684_MODULE>",
          },
          {
            id: "CL_ESP8684_MODULE_ESPC2_01",
            help: null,
            name: "CL_ESP8684_MODULE_ESPC2_01",
            type: "bool",
            range: null,
            title: "ESPC2-01",
            children: [],
            depends_on: "<choice CL_ESP8684_MODULE>",
          },
          {
            id: "CL_ESP8684_MODULE_ESPC2_02",
            help: null,
            name: "CL_ESP8684_MODULE_ESPC2_02",
            type: "bool",
            range: null,
            title: "ESPC2-02",
            children: [],
            depends_on: "<choice CL_ESP8684_MODULE>",
          },
          {
            id: "CL_ESP8684_MODULE_ESPC2_05",
            help: null,
            name: "CL_ESP8684_MODULE_ESPC2_05",
            type: "bool",
            range: null,
            title: "ESPC2-05",
            children: [],
            depends_on: "<choice CL_ESP8684_MODULE>",
          },
          {
            id: "CL_ESP8684_MODULE_ESPC2_12",
            help: null,
            name: "CL_ESP8684_MODULE_ESPC2_12",
            type: "bool",
            range: null,
            title: "ESPC2-12",
            children: [],
            depends_on: "<choice CL_ESP8684_MODULE>",
          },
        ],
        depends_on: "CL_CHIP_TYPE_ESP8684",
      },
      {
        id: "芯片模组-bl602c模组",
        help: null,
        name: "CL_BL602C_MODULE",
        type: "choice",
        title: "BL602C模组",
        children: [
          {
            id: "CL_BL602C_MODULE_NULL",
            help: null,
            name: "CL_BL602C_MODULE_NULL",
            type: "bool",
            range: null,
            title: "不使用模组",
            default: "y",
            children: [],
            depends_on: "<choice CL_BL602C_MODULE>",
          },
          {
            id: "CL_BL602C_MODULE_BL10_2M",
            help: null,
            name: "CL_BL602C_MODULE_BL10_2M",
            type: "bool",
            range: null,
            title: "BL10_2M",
            children: [],
            depends_on: "<choice CL_BL602C_MODULE>",
          },
        ],
        depends_on: "CL_CHIP_TYPE_BL602C",
      },
      {
        id: "芯片模组-bl602l模组",
        help: null,
        name: "CL_BL602L_MODULE",
        type: "choice",
        title: "BL602L模组",
        children: [
          {
            id: "CL_BL602L_MODULE_NULL",
            help: null,
            name: "CL_BL602L_MODULE_NULL",
            type: "bool",
            range: null,
            title: "不使用模组",
            default: "y",
            children: [],
            depends_on: "<choice CL_BL602L_MODULE>",
          },
          {
            id: "CL_BL602L_MODULE_BL200_1M",
            help: null,
            name: "CL_BL602L_MODULE_BL200_1M",
            type: "bool",
            range: null,
            title: "BL200_1M",
            children: [],
            depends_on: "<choice CL_BL602L_MODULE>",
          },
          {
            id: "CL_BL602L_MODULE_BL02_1M",
            help: null,
            name: "CL_BL602L_MODULE_BL02_1M",
            type: "bool",
            range: null,
            title: "BL02_1M",
            children: [],
            depends_on: "<choice CL_BL602L_MODULE>",
          },
          {
            id: "CL_BL602L_MODULE_BL12_1M",
            help: null,
            name: "CL_BL602L_MODULE_BL12_1M",
            type: "bool",
            range: null,
            title: "BL12_1M",
            children: [],
            depends_on: "<choice CL_BL602L_MODULE>",
          },
          {
            id: "CL_BL602L_MODULE_BL12_2M",
            help: null,
            name: "CL_BL602L_MODULE_BL12_2M",
            type: "bool",
            range: null,
            title: "BL12_2M",
            children: [],
            depends_on: "<choice CL_BL602L_MODULE>",
          },
        ],
        depends_on: "CL_CHIP_TYPE_BL602L",
      },
      {
        id: "芯片模组-ln882h模组",
        help: null,
        name: "CL_LN882H_MODULE",
        type: "choice",
        title: "LN882H模组",
        children: [
          {
            id: "CL_LN882H_MODULE_NULL",
            help: null,
            name: "CL_LN882H_MODULE_NULL",
            type: "bool",
            range: null,
            title: "不使用模组",
            default: "y",
            children: [],
            depends_on: "<choice CL_LN882H_MODULE>",
          },
          {
            id: "CL_LN882H_MODULE_LN_02",
            help: null,
            name: "CL_LN882H_MODULE_LN_02",
            type: "bool",
            range: null,
            title: "LN-02",
            children: [],
            depends_on: "<choice CL_LN882H_MODULE>",
          },
          {
            id: "CL_LN882H_MODULE_LN_05",
            help: null,
            name: "CL_LN882H_MODULE_LN_05",
            type: "bool",
            range: null,
            title: "LN-05",
            children: [],
            depends_on: "<choice CL_LN882H_MODULE>",
          },
          {
            id: "CL_LN882H_MODULE_LN_10",
            help: null,
            name: "CL_LN882H_MODULE_LN_10",
            type: "bool",
            range: null,
            title: "LN-10",
            children: [],
            depends_on: "<choice CL_LN882H_MODULE>",
          },
        ],
        depends_on: "CL_CHIP_TYPE_LN882H",
      },
    ],
    depends_on: null,
  },
  {
    id: "产品配置",
    type: "menu",
    title: "产品配置",
    children: [
      {
        id: "产品配置-灯带的类型",
        help: null,
        name: "CL_DREAM_TYPE",
        type: "choice",
        title: "灯带的类型",
        children: [
          {
            id: "CL_DREAM_TYPE_RBG",
            help: null,
            name: "CL_DREAM_TYPE_RBG",
            type: "bool",
            range: null,
            title: "RGB",
            default: "y",
            children: [],
            depends_on: "<choice CL_DREAM_TYPE>",
          },
          {
            id: "CL_DREAM_TYPE_RBGW",
            help: null,
            name: "CL_DREAM_TYPE_RBGW",
            type: "bool",
            range: null,
            title: "RGBW",
            children: [],
            depends_on:
              "(CL_CHIP_TYPE_BL602C || CL_CHIP_TYPE_BL602L) && <choice CL_DREAM_TYPE>",
          },
          {
            id: "CL_DREAM_TYPE_RBGCW",
            help: null,
            name: "CL_DREAM_TYPE_RBGCW",
            type: "bool",
            range: null,
            title: "RGB+CW",
            children: [],
            depends_on: "<choice CL_DREAM_TYPE>",
          },
          {
            id: "CL_DREAM_TYPE_RBGCW_MIX",
            help: null,
            name: "CL_DREAM_TYPE_RBGCW_MIX",
            type: "bool",
            range: null,
            title: "RGBCW_MIX",
            children: [],
            depends_on: "<choice CL_DREAM_TYPE>",
          },
        ],
        depends_on: null,
      },
      {
        id: "产品配置-驱动配置",
        type: "menu",
        title: "驱动配置",
        children: [
          {
            id: "产品配置-驱动配置-rgb",
            type: "menu",
            title: "RGB",
            children: [
              {
                id: "产品配置-驱动配置-rgb-驱动芯片",
                help: null,
                name: "CL_DREAM_RGB_DRIVER_TYPE",
                type: "choice",
                title: "驱动芯片",
                children: [
                  {
                    id: "CL_DREAM_RGB_DRIVER_TYPE_WS2812",
                    help: null,
                    name: "CL_DREAM_RGB_DRIVER_TYPE_WS2812",
                    type: "bool",
                    range: null,
                    title: "WS2812",
                    default: "y",
                    children: [],
                    depends_on: "<choice CL_DREAM_RGB_DRIVER_TYPE>",
                  },
                ],
                depends_on: "CL_DREAM_TYPE_RBG || CL_DREAM_TYPE_RBGCW",
              },
              {
                id: "CL_DREAM_RGB_DRIVER_CHANGE_IO",
                help: null,
                name: "CL_DREAM_RGB_DRIVER_CHANGE_IO",
                type: "menu",
                range: null,
                title: "修改HAL引脚",
                default: "n",
                children: [
                  {
                    id: "CL_DREAM_RGB_DRIVER_CHANGE_IO",
                    help: null,
                    name: "CL_DREAM_RGB_DRIVER_CHANGE_IO",
                    type: "bool",
                    range: null,
                    title: "修改HAL引脚",
                    default: "n",
                    children: [],
                    depends_on: "CL_DREAM_TYPE_RBG || CL_DREAM_TYPE_RBGCW",
                    is_menuconfig: true,
                  },
                  {
                    id: "CL_DREAM_RGB_DRIVER_IO",
                    help: null,
                    name: "CL_DREAM_RGB_DRIVER_IO",
                    type: "int",
                    range: [0, 35],
                    title: "输出引脚",
                    default: "12",
                    children: [],
                    depends_on:
                      "CL_DREAM_RGB_DRIVER_CHANGE_IO && (CL_DREAM_TYPE_RBG || CL_DREAM_TYPE_RBGCW)",
                  },
                ],
                depends_on: "CL_DREAM_TYPE_RBG || CL_DREAM_TYPE_RBGCW",
                is_menuconfig: true,
              },
              {
                id: "CL_DREAM_RBG_POWER_LIMIT",
                help: null,
                name: "CL_DREAM_RBG_POWER_LIMIT",
                type: "bool",
                range: null,
                title: "RGB功率限制",
                default: "n",
                children: [],
                depends_on: "CL_DREAM_TYPE_RBG || CL_DREAM_TYPE_RBGCW",
              },
            ],
            depends_on: "CL_DREAM_TYPE_RBG || CL_DREAM_TYPE_RBGCW",
          },
          {
            id: "产品配置-驱动配置-rgbw",
            type: "menu",
            title: "RGBW",
            children: [
              {
                id: "产品配置-驱动配置-rgbw-驱动芯片",
                help: null,
                name: "CL_DREAM_RGB_DRIVER_TYPE",
                type: "choice",
                title: "驱动芯片",
                children: [
                  {
                    id: "CL_DREAM_RGB_DRIVER_TYPE_WS2814",
                    help: null,
                    name: "CL_DREAM_RGB_DRIVER_TYPE_WS2814",
                    type: "bool",
                    range: null,
                    title: "WS2814",
                    children: [],
                    depends_on: "<choice CL_DREAM_RGB_DRIVER_TYPE>",
                  },
                  {
                    id: "CL_DREAM_RGB_DRIVER_TYPE_SM16714",
                    help: null,
                    name: "CL_DREAM_RGB_DRIVER_TYPE_SM16714",
                    type: "bool",
                    range: null,
                    title: "SM16714",
                    children: [],
                    depends_on: "<choice CL_DREAM_RGB_DRIVER_TYPE>",
                  },
                ],
                depends_on: "CL_DREAM_TYPE_RBGW",
              },
              {
                id: "产品配置-驱动配置-rgbw-sm16714电流配置",
                type: "menu",
                title: "SM16714电流配置",
                children: [
                  {
                    id: "CL_DREAM_LIMIT_R",
                    help: null,
                    name: "CL_DREAM_LIMIT_R",
                    type: "int",
                    range: [1, 32],
                    title: "R最大电流",
                    default: "1",
                    children: [],
                    depends_on:
                      "CL_DREAM_RGB_DRIVER_TYPE_SM16714 && CL_DREAM_TYPE_RBGW",
                  },
                  {
                    id: "CL_DREAM_LIMIT_G",
                    help: null,
                    name: "CL_DREAM_LIMIT_G",
                    type: "int",
                    range: [1, 32],
                    title: "G最大电流",
                    default: "1",
                    children: [],
                    depends_on:
                      "CL_DREAM_RGB_DRIVER_TYPE_SM16714 && CL_DREAM_TYPE_RBGW",
                  },
                  {
                    id: "CL_DREAM_LIMIT_B",
                    help: null,
                    name: "CL_DREAM_LIMIT_B",
                    type: "int",
                    range: [1, 32],
                    title: "B最大电流",
                    default: "1",
                    children: [],
                    depends_on:
                      "CL_DREAM_RGB_DRIVER_TYPE_SM16714 && CL_DREAM_TYPE_RBGW",
                  },
                  {
                    id: "CL_DREAM_LIMIT_W",
                    help: null,
                    name: "CL_DREAM_LIMIT_W",
                    type: "int",
                    range: [1, 32],
                    title: "W最大电流",
                    default: "1",
                    children: [],
                    depends_on:
                      "CL_DREAM_RGB_DRIVER_TYPE_SM16714 && CL_DREAM_TYPE_RBGW",
                  },
                ],
                depends_on:
                  "CL_DREAM_RGB_DRIVER_TYPE_SM16714 && CL_DREAM_TYPE_RBGW",
              },
            ],
            depends_on: "CL_DREAM_TYPE_RBGW",
          },
          {
            id: "产品配置-驱动配置-rgbcw",
            type: "menu",
            title: "RGBCW",
            children: [
              {
                id: "产品配置-驱动配置-rgbcw-驱动芯片",
                help: null,
                name: "CL_DREAM_RGB_DRIVER_TYPE",
                type: "choice",
                title: "驱动芯片",
                children: [
                  {
                    id: "CL_DREAM_RGB_DRIVER_TYPE_UCS2909",
                    help: null,
                    name: "CL_DREAM_RGB_DRIVER_TYPE_UCS2909",
                    type: "bool",
                    range: null,
                    title: "UCS2909",
                    children: [],
                    depends_on: "<choice CL_DREAM_RGB_DRIVER_TYPE>",
                  },
                ],
                depends_on: "CL_DREAM_TYPE_RBGCW_MIX",
              },
              {
                id: "产品配置-驱动配置-rgbcw-ucs2909通道配置",
                type: "menu",
                title: "UCS2909通道配置",
                children: [
                  {
                    id: "CL_DREAM_R_DRIVER_CHANNEL",
                    help: null,
                    name: "CL_DREAM_R_DRIVER_CHANNEL",
                    type: "int",
                    range: [1, 9],
                    title: "R 驱动信道",
                    default: "1",
                    children: [],
                    depends_on:
                      "CL_DREAM_RGB_DRIVER_TYPE_UCS2909 && CL_DREAM_TYPE_RBGCW_MIX",
                  },
                  {
                    id: "CL_DREAM_G_DRIVER_CHANNEL",
                    help: null,
                    name: "CL_DREAM_G_DRIVER_CHANNEL",
                    type: "int",
                    range: [1, 9],
                    title: "G 驱动信道",
                    default: "2",
                    children: [],
                    depends_on:
                      "CL_DREAM_RGB_DRIVER_TYPE_UCS2909 && CL_DREAM_TYPE_RBGCW_MIX",
                  },
                  {
                    id: "CL_DREAM_B_DRIVER_CHANNEL",
                    help: null,
                    name: "CL_DREAM_B_DRIVER_CHANNEL",
                    type: "int",
                    range: [1, 9],
                    title: "B 驱动信道",
                    default: "3",
                    children: [],
                    depends_on:
                      "CL_DREAM_RGB_DRIVER_TYPE_UCS2909 && CL_DREAM_TYPE_RBGCW_MIX",
                  },
                  {
                    id: "CL_DREAM_C_DRIVER_CHANNEL",
                    help: null,
                    name: "CL_DREAM_C_DRIVER_CHANNEL",
                    type: "int",
                    range: [1, 9],
                    title: "C 驱动信道",
                    default: "4",
                    children: [],
                    depends_on:
                      "CL_DREAM_RGB_DRIVER_TYPE_UCS2909 && CL_DREAM_TYPE_RBGCW_MIX",
                  },
                  {
                    id: "CL_DREAM_W_DRIVER_CHANNEL",
                    help: null,
                    name: "CL_DREAM_W_DRIVER_CHANNEL",
                    type: "int",
                    range: [1, 9],
                    title: "W 驱动信道",
                    default: "5",
                    children: [],
                    depends_on:
                      "CL_DREAM_RGB_DRIVER_TYPE_UCS2909 && CL_DREAM_TYPE_RBGCW_MIX",
                  },
                ],
                depends_on:
                  "CL_DREAM_RGB_DRIVER_TYPE_UCS2909 && CL_DREAM_TYPE_RBGCW_MIX",
              },
              {
                id: "产品配置-驱动配置-rgbcw-色温输出方式",
                help: null,
                name: "CL_DREAM_CW_OUT_TYPE",
                type: "choice",
                title: "色温输出方式",
                children: [
                  {
                    id: "CL_DREAM_CW_OUT_TYPE_FULLPOWER",
                    help: null,
                    name: "CL_DREAM_CW_OUT_TYPE_FULLPOWER",
                    type: "bool",
                    range: null,
                    title: "全功率",
                    default: "y",
                    children: [],
                    depends_on: "<choice CL_DREAM_CW_OUT_TYPE>",
                  },
                  {
                    id: "CL_DREAM_CW_OUT_TYPE_HALFPOWER",
                    help: null,
                    name: "CL_DREAM_CW_OUT_TYPE_HALFPOWER",
                    type: "bool",
                    range: null,
                    title: "半功率",
                    children: [],
                    depends_on: "<choice CL_DREAM_CW_OUT_TYPE>",
                  },
                ],
                depends_on:
                  "CL_DREAM_TYPE_RBGCW_MIX && CL_DREAM_TYPE_RBGCW_MIX",
              },
            ],
            depends_on: "CL_DREAM_TYPE_RBGCW_MIX",
          },
          {
            id: "产品配置-驱动配置-cw",
            type: "menu",
            title: "CW",
            children: [
              {
                id: "CL_DREAM_USE_PWM_DRIVER",
                help: null,
                name: "CL_DREAM_USE_PWM_DRIVER",
                type: "menu",
                range: null,
                title: "使能PWM驱动",
                default: "y",
                children: [
                  {
                    id: "CL_DREAM_USE_PWM_DRIVER",
                    help: null,
                    name: "CL_DREAM_USE_PWM_DRIVER",
                    type: "bool",
                    range: null,
                    title: "使能PWM驱动",
                    default: "y",
                    children: [],
                    depends_on: "CL_DREAM_TYPE_RBGCW",
                    is_menuconfig: true,
                  },
                  {
                    id: "CL_DREAM_PWM_DRIVER_FREQ",
                    help: null,
                    name: "CL_DREAM_PWM_DRIVER_FREQ",
                    type: "int",
                    range: [10, 20000],
                    title: "PWM频率",
                    default: "5000",
                    children: [],
                    depends_on:
                      "CL_DREAM_USE_PWM_DRIVER && CL_DREAM_TYPE_RBGCW",
                  },
                  {
                    id: "CL_DREAM_PWM_DRIVER_ACTIVE_LEVEL_HIGH",
                    help: null,
                    name: "CL_DREAM_PWM_DRIVER_ACTIVE_LEVEL_HIGH",
                    type: "bool",
                    range: null,
                    title: "高电平有效",
                    default: "y",
                    children: [],
                    depends_on:
                      "CL_DREAM_USE_PWM_DRIVER && CL_DREAM_TYPE_RBGCW",
                  },
                ],
                depends_on: "CL_DREAM_TYPE_RBGCW",
                is_menuconfig: true,
              },
              {
                id: "产品配置-驱动配置-cw-c",
                type: "menu",
                title: "C",
                children: [
                  {
                    id: "产品配置-驱动配置-cw-c-驱动方式",
                    help: null,
                    name: "CL_DREAM_C_DRIVER_TYPE",
                    type: "choice",
                    title: "驱动方式",
                    children: [
                      {
                        id: "CL_DREAM_C_DRIVER_TYPE_PWM",
                        help: null,
                        name: "CL_DREAM_C_DRIVER_TYPE_PWM",
                        type: "bool",
                        range: null,
                        title: "PWM",
                        default: "y",
                        children: [],
                        depends_on: "<choice CL_DREAM_C_DRIVER_TYPE>",
                      },
                    ],
                    depends_on: "CL_DREAM_TYPE_RBGCW && CL_DREAM_TYPE_RBGCW",
                  },
                  {
                    id: "CL_DREAM_C_DRIVER_CHANNEL",
                    help: null,
                    name: "CL_DREAM_C_DRIVER_CHANNEL",
                    type: "int",
                    range: [1, 9],
                    title: "C 驱动信道",
                    default: "4",
                    children: [],
                    depends_on: "CL_DREAM_TYPE_RBGCW && CL_DREAM_TYPE_RBGCW",
                  },
                  {
                    id: "CL_DREAM_C_DRIVER_PWM_IO",
                    help: null,
                    name: "CL_DREAM_C_DRIVER_PWM_IO",
                    type: "int",
                    range: [0, 36],
                    title: "PWM引脚",
                    default: "14",
                    children: [],
                    depends_on:
                      "CL_DREAM_C_DRIVER_TYPE_PWM && CL_DREAM_TYPE_RBGCW && CL_DREAM_TYPE_RBGCW",
                  },
                ],
                depends_on: "CL_DREAM_TYPE_RBGCW && CL_DREAM_TYPE_RBGCW",
              },
              {
                id: "产品配置-驱动配置-cw-w",
                type: "menu",
                title: "W",
                children: [
                  {
                    id: "产品配置-驱动配置-cw-w-驱动方式",
                    help: null,
                    name: "CL_DREAM_W_DRIVER_TYPE",
                    type: "choice",
                    title: "驱动方式",
                    children: [
                      {
                        id: "CL_DREAM_W_DRIVER_TYPE_PWM",
                        help: null,
                        name: "CL_DREAM_W_DRIVER_TYPE_PWM",
                        type: "bool",
                        range: null,
                        title: "PWM",
                        default: "y",
                        children: [],
                        depends_on: "<choice CL_DREAM_W_DRIVER_TYPE>",
                      },
                    ],
                    depends_on:
                      "(CL_DREAM_TYPE_RBGW || CL_DREAM_TYPE_RBGCW) && CL_DREAM_TYPE_RBGCW",
                  },
                  {
                    id: "CL_DREAM_W_DRIVER_CHANNEL",
                    help: null,
                    name: "CL_DREAM_W_DRIVER_CHANNEL",
                    type: "int",
                    range: [1, 9],
                    title: "W 驱动信道",
                    default: "5",
                    children: [],
                    depends_on:
                      "(CL_DREAM_TYPE_RBGW || CL_DREAM_TYPE_RBGCW) && CL_DREAM_TYPE_RBGCW",
                  },
                  {
                    id: "CL_DREAM_W_DRIVER_PWM_IO",
                    help: null,
                    name: "CL_DREAM_W_DRIVER_PWM_IO",
                    type: "int",
                    range: [0, 36],
                    title: "PWM引脚",
                    default: "14",
                    children: [],
                    depends_on:
                      "CL_DREAM_W_DRIVER_TYPE_PWM && (CL_DREAM_TYPE_RBGW || CL_DREAM_TYPE_RBGCW) && CL_DREAM_TYPE_RBGCW",
                  },
                ],
                depends_on:
                  "(CL_DREAM_TYPE_RBGW || CL_DREAM_TYPE_RBGCW) && CL_DREAM_TYPE_RBGCW",
              },
              {
                id: "产品配置-驱动配置-cw-色温输出方式",
                help: null,
                name: "CL_DREAM_CW_OUT_TYPE",
                type: "choice",
                title: "色温输出方式",
                children: [
                  {
                    id: "CL_DREAM_CW_OUT_TYPE_FULLPOWER",
                    help: null,
                    name: "CL_DREAM_CW_OUT_TYPE_FULLPOWER",
                    type: "bool",
                    range: null,
                    title: "全功率",
                    default: "y",
                    children: [],
                    depends_on: "<choice CL_DREAM_CW_OUT_TYPE>",
                  },
                  {
                    id: "CL_DREAM_CW_OUT_TYPE_HALFPOWER",
                    help: null,
                    name: "CL_DREAM_CW_OUT_TYPE_HALFPOWER",
                    type: "bool",
                    range: null,
                    title: "半功率",
                    children: [],
                    depends_on: "<choice CL_DREAM_CW_OUT_TYPE>",
                  },
                  {
                    id: "CL_DREAM_CW_OUT_TYPE_CW2RGB",
                    help: null,
                    name: "CL_DREAM_CW_OUT_TYPE_CW2RGB",
                    type: "bool",
                    range: null,
                    title: "RGB混色",
                    children: [],
                    depends_on: "<choice CL_DREAM_CW_OUT_TYPE>",
                  },
                ],
                depends_on: "CL_DREAM_TYPE_RBGCW && CL_DREAM_TYPE_RBGCW",
              },
              {
                id: "CL_DREAM_CW_POWER_LIMIT",
                help: null,
                name: "CL_DREAM_CW_POWER_LIMIT",
                type: "bool",
                range: null,
                title: "CW功率限制",
                default: "n",
                children: [],
                depends_on: "CL_DREAM_TYPE_RBGCW",
              },
            ],
            depends_on: "CL_DREAM_TYPE_RBGCW",
          },
        ],
        depends_on: null,
      },
      {
        id: "产品配置-默认状态设置",
        type: "menu",
        title: "默认状态设置",
        children: [
          {
            id: "CL_DREAM_FIRST_WIFI_CFG_STATUS",
            help: null,
            name: "CL_DREAM_FIRST_WIFI_CFG_STATUS",
            type: "bool",
            range: null,
            title: "首次配网开启配网状态提醒",
            default: "y",
            children: [],
            depends_on: null,
          },
          {
            id: "产品配置-默认状态设置-rgb线序",
            help: null,
            name: "CL_DREAM_DEFAULT_RGB_TURN",
            type: "choice",
            title: "RGB线序",
            children: [
              {
                id: "CL_DREAM_DEFAULT_RGB_TURN_GRB",
                help: null,
                name: "CL_DREAM_DEFAULT_RGB_TURN_GRB",
                type: "bool",
                range: null,
                title: "GRB",
                default: "y",
                children: [],
                depends_on: "<choice CL_DREAM_DEFAULT_RGB_TURN>",
              },
              {
                id: "CL_DREAM_DEFAULT_RGB_TURN_RGB",
                help: null,
                name: "CL_DREAM_DEFAULT_RGB_TURN_RGB",
                type: "bool",
                range: null,
                title: "RGB",
                children: [],
                depends_on: "<choice CL_DREAM_DEFAULT_RGB_TURN>",
              },
              {
                id: "CL_DREAM_DEFAULT_RGB_TURN_GBR",
                help: null,
                name: "CL_DREAM_DEFAULT_RGB_TURN_GBR",
                type: "bool",
                range: null,
                title: "GBR",
                children: [],
                depends_on: "<choice CL_DREAM_DEFAULT_RGB_TURN>",
              },
              {
                id: "CL_DREAM_DEFAULT_RGB_TURN_RBG",
                help: null,
                name: "CL_DREAM_DEFAULT_RGB_TURN_RBG",
                type: "bool",
                range: null,
                title: "RBG",
                children: [],
                depends_on: "<choice CL_DREAM_DEFAULT_RGB_TURN>",
              },
              {
                id: "CL_DREAM_DEFAULT_RGB_TURN_BRG",
                help: null,
                name: "CL_DREAM_DEFAULT_RGB_TURN_BRG",
                type: "bool",
                range: null,
                title: "BRG",
                children: [],
                depends_on: "<choice CL_DREAM_DEFAULT_RGB_TURN>",
              },
              {
                id: "CL_DREAM_DEFAULT_RGB_TURN_BGR",
                help: null,
                name: "CL_DREAM_DEFAULT_RGB_TURN_BGR",
                type: "bool",
                range: null,
                title: "BGR",
                children: [],
                depends_on: "<choice CL_DREAM_DEFAULT_RGB_TURN>",
              },
            ],
            depends_on: null,
          },
          {
            id: "CL_DREAM_DEFAULT_CHIC_POINT",
            help: null,
            name: "CL_DREAM_DEFAULT_CHIC_POINT",
            type: "int",
            range: [0, 300],
            title: "默认灯带数量",
            default: "60",
            children: [],
            depends_on: null,
          },
          {
            id: "CL_DREAM_DEFAULT_COLOR",
            help: null,
            name: "CL_DREAM_DEFAULT_COLOR",
            type: "string",
            range: null,
            title: "默认颜色",
            default: '"000003E8FFFF"',
            children: [],
            depends_on: null,
          },
          {
            id: "CL_DREAM_DEFAULT_DIY_DATA",
            help: null,
            name: "CL_DREAM_DEFAULT_DIY_DATA",
            type: "string",
            range: null,
            title: "默认DIY效果",
            default:
              '"000003E8FFFF002003E8FFFF004003E8FFFF001003E8FFFF003003E8FFFF005003E8FFFF001503E8FFFF0102FFFFFFFFFFFFFFFF46"',
            children: [],
            depends_on: null,
          },
          {
            id: "CL_DREAM_DEFAULT_BRIGHT",
            help: null,
            name: "CL_DREAM_DEFAULT_BRIGHT",
            type: "int",
            range: [0, 1000],
            title: "默认亮度",
            default: "1000",
            children: [],
            depends_on: null,
          },
          {
            id: "CL_DREAM_DEFAULT_SPEED",
            help: null,
            name: "CL_DREAM_DEFAULT_SPEED",
            type: "int",
            range: [0, 1000],
            title: "默认速度",
            default: "700",
            children: [],
            depends_on: null,
          },
          {
            id: "CL_DREAM_DEFAULT_SENCE_INDEX",
            help: null,
            name: "CL_DREAM_DEFAULT_SENCE_INDEX",
            type: "int",
            range: [0, 100],
            title: "默认场景模式",
            default: "20",
            children: [],
            depends_on: null,
          },
          {
            id: "CL_DREAM_DEFAULT_STATIC_FADE",
            help: null,
            name: "CL_DREAM_DEFAULT_STATIC_FADE",
            type: "bool",
            range: null,
            title: "颜色过度",
            children: [],
            depends_on: null,
          },
        ],
        depends_on: null,
      },
      {
        id: "CL_POWER_SWITCH_CONFIG",
        help: null,
        name: "CL_POWER_SWITCH_CONFIG",
        type: "menu",
        range: null,
        title: "使能多次上电配网",
        default: "y",
        children: [
          {
            id: "CL_POWER_SWITCH_CONFIG",
            help: null,
            name: "CL_POWER_SWITCH_CONFIG",
            type: "bool",
            range: null,
            title: "使能多次上电配网",
            default: "y",
            children: [],
            depends_on: null,
            is_menuconfig: true,
          },
          {
            id: "CL_POWER_SWITCH_CONFIG_COUNT",
            help: null,
            name: "CL_POWER_SWITCH_CONFIG_COUNT",
            type: "int",
            range: null,
            title: "重复上电次数",
            default: "3",
            children: [],
            depends_on: "CL_POWER_SWITCH_CONFIG",
          },
          {
            id: "CL_POWER_SWITCH_CONFIG_CLEAN_TIME",
            help: null,
            name: "CL_POWER_SWITCH_CONFIG_CLEAN_TIME",
            type: "int",
            range: null,
            title: "清除时间",
            default: "5000",
            children: [],
            depends_on: "CL_POWER_SWITCH_CONFIG",
          },
        ],
        depends_on: null,
        is_menuconfig: true,
      },
      {
        id: "CL_MUSIC_MODE",
        help: null,
        name: "CL_MUSIC_MODE",
        type: "menu",
        range: null,
        title: "使能音乐模式",
        default: "y",
        children: [
          {
            id: "CL_MUSIC_MODE",
            help: null,
            name: "CL_MUSIC_MODE",
            type: "bool",
            range: null,
            title: "使能音乐模式",
            default: "y",
            children: [],
            depends_on: null,
            is_menuconfig: true,
          },
          {
            id: "CL_MUSIC_MODE_OUT",
            help: null,
            name: "CL_MUSIC_MODE_OUT",
            type: "menu",
            range: null,
            title: "设备麦音乐模式",
            default: "y",
            children: [
              {
                id: "CL_MUSIC_MODE_OUT",
                help: null,
                name: "CL_MUSIC_MODE_OUT",
                type: "bool",
                range: null,
                title: "设备麦音乐模式",
                default: "y",
                children: [],
                depends_on: "CL_MUSIC_MODE",
                is_menuconfig: true,
              },
              {
                id: "CL_MUSIC_MODE_OUT_ADC_PIN",
                help: null,
                name: "CL_MUSIC_MODE_OUT_ADC_PIN",
                type: "int",
                range: null,
                title: "设备ADC引脚",
                default: "5",
                children: [],
                depends_on: "CL_MUSIC_MODE_OUT && CL_MUSIC_MODE",
              },
              {
                id: "CL_MUSIC_MODE_OUT_SEN_DIFF_VAL",
                help: null,
                name: "CL_MUSIC_MODE_OUT_SEN_DIFF_VAL",
                type: "int",
                range: null,
                title: "设备麦灵敏度差分值",
                default: "150",
                children: [],
                depends_on: "CL_MUSIC_MODE_OUT && CL_MUSIC_MODE",
              },
              {
                id: "CL_MUSIC_MODE_OUT_AMP_PROP_VAL",
                help: null,
                name: "CL_MUSIC_MODE_OUT_AMP_PROP_VAL",
                type: "int",
                range: null,
                title: "设备麦幅度比例缩减值",
                default: "10",
                children: [],
                depends_on: "CL_MUSIC_MODE_OUT && CL_MUSIC_MODE",
              },
            ],
            depends_on: "CL_MUSIC_MODE",
            is_menuconfig: true,
          },
          {
            id: "CL_MUSIC_MODE_INT",
            help: null,
            name: "CL_MUSIC_MODE_INT",
            type: "menu",
            range: null,
            title: "手机麦音乐模式",
            default: "y",
            children: [
              {
                id: "CL_MUSIC_MODE_INT",
                help: null,
                name: "CL_MUSIC_MODE_INT",
                type: "bool",
                range: null,
                title: "手机麦音乐模式",
                default: "y",
                children: [],
                depends_on: "CL_MUSIC_MODE",
                is_menuconfig: true,
              },
              {
                id: "CL_MUSIC_MODE_INT_INS_POINT",
                help: null,
                name: "CL_MUSIC_MODE_INT_INS_POINT",
                type: "int",
                range: null,
                title: "手机麦频谱点数",
                default: "12",
                children: [],
                depends_on: "CL_MUSIC_MODE_INT && CL_MUSIC_MODE",
              },
              {
                id: "CL_MUSIC_MODE_INT_SEN_DIFF_VAL",
                help: null,
                name: "CL_MUSIC_MODE_INT_SEN_DIFF_VAL",
                type: "int",
                range: null,
                title: "手机麦灵敏度差分值",
                default: "100",
                children: [],
                depends_on: "CL_MUSIC_MODE_INT && CL_MUSIC_MODE",
              },
              {
                id: "CL_MUSIC_MODE_INT_AMP_PROP_VAL",
                help: null,
                name: "CL_MUSIC_MODE_INT_AMP_PROP_VAL",
                type: "int",
                range: null,
                title: "手机麦幅度比例缩减值",
                default: "10",
                children: [],
                depends_on: "CL_MUSIC_MODE_INT && CL_MUSIC_MODE",
              },
            ],
            depends_on: "CL_MUSIC_MODE",
            is_menuconfig: true,
          },
          {
            id: "CL_MUSIC_MODE_SENSITIVITY",
            help: null,
            name: "CL_MUSIC_MODE_SENSITIVITY",
            type: "int",
            range: [0, 100],
            title: "默认灵敏度",
            default: "60",
            children: [],
            depends_on: "CL_MUSIC_MODE",
          },
          {
            id: "CL_MUSIC_MODE_INDEX",
            help: null,
            name: "CL_MUSIC_MODE_INDEX",
            type: "int",
            range: null,
            title: "默认音乐效果",
            default: "0",
            children: [],
            depends_on: "CL_MUSIC_MODE",
          },
        ],
        depends_on: null,
        is_menuconfig: true,
      },
      {
        id: "CL_REMOTE_CONTROL",
        help: null,
        name: "CL_REMOTE_CONTROL",
        type: "menu",
        range: null,
        title: "使能遥控控制",
        default: "n",
        children: [
          {
            id: "CL_REMOTE_CONTROL",
            help: null,
            name: "CL_REMOTE_CONTROL",
            type: "bool",
            range: null,
            title: "使能遥控控制",
            default: "n",
            children: [],
            depends_on: null,
            is_menuconfig: true,
          },
          {
            id: "产品配置-使能遥控控制-遥控控制方式",
            help: null,
            name: "CL_REMOTE_CONTROL_TYPE",
            type: "choice",
            title: "遥控控制方式",
            children: [
              {
                id: "CL_REMOTE_CONTROL_TYPE_IR",
                help: null,
                name: "CL_REMOTE_CONTROL_TYPE_IR",
                type: "bool",
                range: null,
                title: "红外",
                default: "y",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_TYPE>",
              },
              {
                id: "CONFIG_REMOTE_CONTROL_WAY_RF",
                help: null,
                name: "CONFIG_REMOTE_CONTROL_WAY_RF",
                type: "bool",
                range: null,
                title: "433",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_TYPE>",
              },
              {
                id: "CL_REMOTE_CONTROL_TYPE_BLE",
                help: null,
                name: "CL_REMOTE_CONTROL_TYPE_BLE",
                type: "bool",
                range: null,
                title: "蓝牙2.4G",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_TYPE>",
              },
              {
                id: "CL_REMOTE_CONTROL_TYPE_USER_DEFINE",
                help: null,
                name: "CL_REMOTE_CONTROL_TYPE_USER_DEFINE",
                type: "bool",
                range: null,
                title: "宏定义",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_TYPE>",
              },
            ],
            depends_on: "CL_REMOTE_CONTROL",
          },
          {
            id: "CL_IR_CONTROL_PIN",
            help: null,
            name: "CL_IR_CONTROL_PIN",
            type: "int",
            range: [0, 35],
            title: "红外驱动引脚",
            default: "12",
            children: [],
            depends_on: "CL_REMOTE_CONTROL_TYPE_IR && CL_REMOTE_CONTROL",
          },
          {
            id: "产品配置-使能遥控控制-遥控控制模型",
            help: null,
            name: "CL_REMOTE_CONTROL_MODEL",
            type: "choice",
            title: "遥控控制模型",
            children: [
              {
                id: "CL_REMOTE_CONTROL_MODEL_IR_24_1",
                help: null,
                name: "CL_REMOTE_CONTROL_MODEL_IR_24_1",
                type: "bool",
                range: null,
                title: "IR_24_1",
                default: "y",
                children: [],
                depends_on:
                  "CL_REMOTE_CONTROL_TYPE_IR && <choice CL_REMOTE_CONTROL_MODEL>",
              },
              {
                id: "CL_REMOTE_CONTROL_MODEL_IR_24_2",
                help: null,
                name: "CL_REMOTE_CONTROL_MODEL_IR_24_2",
                type: "bool",
                range: null,
                title: "IR_24_2",
                children: [],
                depends_on:
                  "CL_REMOTE_CONTROL_TYPE_IR && <choice CL_REMOTE_CONTROL_MODEL>",
              },
              {
                id: "CL_REMOTE_CONTROL_MODEL_BLE_COXYLIFE",
                help: null,
                name: "CL_REMOTE_CONTROL_MODEL_BLE_COXYLIFE",
                type: "bool",
                range: null,
                title: "BLE_CozyLife",
                children: [],
                depends_on:
                  "CL_REMOTE_CONTROL_TYPE_BLE && <choice CL_REMOTE_CONTROL_MODEL>",
              },
              {
                id: "CL_REMOTE_CONTROL_MODEL_BLE_12_1",
                help: null,
                name: "CL_REMOTE_CONTROL_MODEL_BLE_12_1",
                type: "bool",
                range: null,
                title: "BLE_12_1",
                children: [],
                depends_on:
                  "CL_REMOTE_CONTROL_TYPE_BLE && <choice CL_REMOTE_CONTROL_MODEL>",
              },
              {
                id: "CL_REMOTE_CONTROL_MODEL_NONE",
                help: null,
                name: "CL_REMOTE_CONTROL_MODEL_NONE",
                type: "bool",
                range: null,
                title: "用户自定义",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_MODEL>",
              },
            ],
            depends_on: "CL_REMOTE_CONTROL",
          },
        ],
        depends_on: null,
        is_menuconfig: true,
      },
      {
        id: "产品配置--type-menu2-",
        type: "menu2",
        title: "",
        children: [
          {
            id: "CL_REMOTE_CONTROL_-id-_CODE",
            help: null,
            name: "CL_REMOTE_CONTROL_-id-_CODE",
            type: "int",
            range: [0, 65635],
            title: "Code",
            default: "0",
            children: [],
            placement: "left",
            depends_on: "CL_REMOTE_CONTROL",
          },
          {
            id: "产品配置--type-menu2--fun-placement-middle-",
            help: null,
            name: "CL_REMOTE_CONTROL_-id-_FUN",
            type: "choice",
            title: "Fun",
            children: [
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_remote_lock_and_unlock",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_remote_lock_and_unlock",
                type: "bool",
                range: null,
                title: "锁定",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_bright_change",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_bright_change",
                type: "bool",
                range: null,
                title: "亮度改变(step:1-1000,dirt:0|1)",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_light_on",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_light_on",
                type: "bool",
                range: null,
                title: "开灯",
                default: "y",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_light_off",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_light_off",
                type: "bool",
                range: null,
                title: "关灯",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_auto_scene_mode",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_auto_scene_mode",
                type: "bool",
                range: null,
                title: "自动场景",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_music_mode",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_music_mode",
                type: "bool",
                range: null,
                title: "音乐模式(index:0-3)",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_countdown",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_countdown",
                type: "bool",
                range: null,
                title: "定时(sec:int)",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_speed",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_speed",
                type: "bool",
                range: null,
                title: "速度+",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_speed",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_speed",
                type: "bool",
                range: null,
                title: "速度-",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_bright",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_bright",
                type: "bool",
                range: null,
                title: "设置亮度(bright:1-1000)",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_bright",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_bright",
                type: "bool",
                range: null,
                title: "亮度+",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_bright",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_bright",
                type: "bool",
                range: null,
                title: "亮度-",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_bright_flash_white",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_bright_flash_white",
                type: "bool",
                range: null,
                title: "亮度+(闪灯)",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_bright_flash_white",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_bright_flash_white",
                type: "bool",
                range: null,
                title: "亮度+(闪灯)",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_color",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_color",
                type: "bool",
                range: null,
                title: "设置颜色(h,s,t)",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_toggle_color_16",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_toggle_color_16",
                type: "bool",
                range: null,
                title: "颜色翻转",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_scene_mode",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_scene_mode",
                type: "bool",
                range: null,
                title: "模式+",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_scene_mode",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_scene_mode",
                type: "bool",
                range: null,
                title: "模式-",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_scene_mode",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_scene_mode",
                type: "bool",
                range: null,
                title: "设置模式(index:int)",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_diy",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_diy",
                type: "bool",
                range: null,
                title: "DIY模式+",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_diy",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_diy",
                type: "bool",
                range: null,
                title: "DIY模式-",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_music_mode",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_music_mode",
                type: "bool",
                range: null,
                title: "音乐模式+",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_music_mode",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_music_mode",
                type: "bool",
                range: null,
                title: "音乐模式-",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_music_1_or_2",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_music_1_or_2",
                type: "bool",
                range: null,
                title: "音乐模式1或2",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_music_3_or_4",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_music_3_or_4",
                type: "bool",
                range: null,
                title: "音乐模式3或4",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_sensitivity",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_sensitivity",
                type: "bool",
                range: null,
                title: "设置灵敏度(senc:0-100)",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_sensitivity",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_increase_sensitivity",
                type: "bool",
                range: null,
                title: "灵敏度+",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_sensitivity",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_decrease_sensitivity",
                type: "bool",
                range: null,
                title: "灵敏度-",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_enter_music_increase_sensitivity",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_enter_music_increase_sensitivity",
                type: "bool",
                range: null,
                title: "灵敏度+(强制进音乐模式)",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_enter_music_decrease_sensitivity",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_enter_music_decrease_sensitivity",
                type: "bool",
                range: null,
                title: "灵敏度-(强制进音乐模式)",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_rgb_index",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_rgb_index",
                type: "bool",
                range: null,
                title: "R->G->B",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_rgb_scene_and_off",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_rgb_scene_and_off",
                type: "bool",
                range: null,
                title: "RGB场景",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_7_color_and_scene",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_7_color_and_scene",
                type: "bool",
                range: null,
                title: "7色场景循环",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_7_color",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_7_color",
                type: "bool",
                range: null,
                title: "7色循环",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_on_and_off",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_on_and_off",
                type: "bool",
                range: null,
                title: "开关",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_start_wifi_config",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_start_wifi_config",
                type: "bool",
                range: null,
                title: "进入配网",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
              {
                id: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_M",
                help: null,
                name: "CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_M",
                type: "bool",
                range: null,
                title: "循环",
                children: [],
                depends_on: "<choice CL_REMOTE_CONTROL_-id-_FUN>",
              },
            ],
            placement: "middle",
            depends_on: "CL_REMOTE_CONTROL",
          },
          {
            id: "CL_REMOTE_CONTROL_-id-_FUN_arg",
            help: null,
            name: "CL_REMOTE_CONTROL_-id-_FUN_arg",
            type: "string",
            range: null,
            title: "",
            default: '""',
            children: [],
            placement: "right",
            depends_on:
              "(CL_REMOTE_CONTROL_-id-_FUN_fun_bright_change || CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_music_mode || CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_countdown || CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_bright || CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_color || CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_scene_mode || CL_REMOTE_CONTROL_-id-_FUN_fun_btn_remote_fun_set_sensitivity) && CL_REMOTE_CONTROL",
          },
        ],
        depends_on: "CL_REMOTE_CONTROL",
      },
      {
        id: "CL_KEY_CONTROL",
        help: null,
        name: "CL_KEY_CONTROL",
        type: "menu",
        range: null,
        title: "使能按键控制",
        default: "n",
        children: [
          {
            id: "CL_KEY_CONTROL",
            help: null,
            name: "CL_KEY_CONTROL",
            type: "bool",
            range: null,
            title: "使能按键控制",
            default: "n",
            children: [],
            depends_on: null,
            is_menuconfig: true,
          },
          {
            id: "产品配置-使能按键控制-按键控制模型",
            help: null,
            name: "CL_KEY_CONTROL_MODEL",
            type: "choice",
            title: "按键控制模型",
            children: [
              {
                id: "CL_KEY_CONTROL_MODEL_1_1",
                help: null,
                name: "CL_KEY_CONTROL_MODEL_1_1",
                type: "bool",
                range: null,
                title: "KEY_1_1",
                default: "y",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_MODEL>",
              },
              {
                id: "CL_KEY_CONTROL_MODEL_3_1",
                help: null,
                name: "CL_KEY_CONTROL_MODEL_3_1",
                type: "bool",
                range: null,
                title: "KEY_3_1",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_MODEL>",
              },
              {
                id: "CL_KEY_CONTROL_MODEL_NONE",
                help: null,
                name: "CL_KEY_CONTROL_MODEL_NONE",
                type: "bool",
                range: null,
                title: "用户自定义",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_MODEL>",
              },
            ],
            depends_on: "CL_KEY_CONTROL",
          },
          {
            id: "CL_KEY_CONTROL_PIN1",
            help: null,
            name: "CL_KEY_CONTROL_PIN1",
            type: "int",
            range: [0, 35],
            title: "按键1引脚",
            default: "20",
            children: [],
            depends_on:
              "(CL_KEY_CONTROL_MODEL_1_1 || CL_KEY_CONTROL_MODEL_3_1) && CL_KEY_CONTROL",
          },
          {
            id: "CL_KEY_CONTROL_PIN2",
            help: null,
            name: "CL_KEY_CONTROL_PIN2",
            type: "int",
            range: [0, 35],
            title: "按键1引脚",
            default: "21",
            children: [],
            depends_on: "CL_KEY_CONTROL_MODEL_3_1 && CL_KEY_CONTROL",
          },
          {
            id: "CL_KEY_CONTROL_PIN3",
            help: null,
            name: "CL_KEY_CONTROL_PIN3",
            type: "int",
            range: [0, 35],
            title: "按键2引脚",
            default: "22",
            children: [],
            depends_on: "CL_KEY_CONTROL_MODEL_3_1 && CL_KEY_CONTROL",
          },
        ],
        depends_on: null,
        is_menuconfig: true,
      },
      {
        id: "产品配置--type-menu2-",
        type: "menu2",
        title: "",
        children: [
          {
            id: "CL_KEY_CONTROL_-id-_CODE",
            help: null,
            name: "CL_KEY_CONTROL_-id-_CODE",
            type: "int",
            range: [0, 36],
            title: "Code",
            children: [],
            placement: "left",
            depends_on: "CL_KEY_CONTROL_MODEL_NONE",
          },
          {
            id: "产品配置--type-menu2--fun-placement-middle-",
            help: null,
            name: "CL_KEY_CONTROL_-id-_CLICK_FUN",
            type: "choice",
            title: "Fun",
            children: [
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_null",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_null",
                type: "bool",
                range: null,
                title: "不设置",
                default: "y",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_remote_lock_and_unlock",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_remote_lock_and_unlock",
                type: "bool",
                range: null,
                title: "锁定",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_bright_change",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_bright_change",
                type: "bool",
                range: null,
                title: "亮度改变(step:1-1000,dirt:0|1)",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_light_on",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_light_on",
                type: "bool",
                range: null,
                title: "开灯",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_light_off",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_light_off",
                type: "bool",
                range: null,
                title: "关灯",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_auto_scene_mode",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_auto_scene_mode",
                type: "bool",
                range: null,
                title: "自动场景",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_set_music_mode",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_set_music_mode",
                type: "bool",
                range: null,
                title: "音乐模式(index:0-3)",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_set_countdown",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_set_countdown",
                type: "bool",
                range: null,
                title: "定时(sec:int)",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_increase_speed",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_increase_speed",
                type: "bool",
                range: null,
                title: "速度+",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_decrease_speed",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_decrease_speed",
                type: "bool",
                range: null,
                title: "速度-",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_set_bright",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_set_bright",
                type: "bool",
                range: null,
                title: "设置亮度(bright:1-1000)",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_increase_bright",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_increase_bright",
                type: "bool",
                range: null,
                title: "亮度+",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_decrease_bright",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_decrease_bright",
                type: "bool",
                range: null,
                title: "亮度-",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_increase_bright_flash_white",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_increase_bright_flash_white",
                type: "bool",
                range: null,
                title: "亮度+(闪灯)",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_decrease_bright_flash_white",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_decrease_bright_flash_white",
                type: "bool",
                range: null,
                title: "亮度+(闪灯)",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_set_color",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_set_color",
                type: "bool",
                range: null,
                title: "设置颜色(h,s,t)",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_toggle_color_16",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_toggle_color_16",
                type: "bool",
                range: null,
                title: "颜色翻转",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_increase_scene_mode",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_increase_scene_mode",
                type: "bool",
                range: null,
                title: "模式+",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_decrease_scene_mode",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_decrease_scene_mode",
                type: "bool",
                range: null,
                title: "模式-",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_set_scene_mode",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_set_scene_mode",
                type: "bool",
                range: null,
                title: "设置模式(index:int)",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_increase_diy",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_increase_diy",
                type: "bool",
                range: null,
                title: "DIY模式+",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_decrease_diy",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_decrease_diy",
                type: "bool",
                range: null,
                title: "DIY模式-",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_increase_music_mode",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_increase_music_mode",
                type: "bool",
                range: null,
                title: "音乐模式+",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_decrease_music_mode",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_decrease_music_mode",
                type: "bool",
                range: null,
                title: "音乐模式-",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_music_1_or_2",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_music_1_or_2",
                type: "bool",
                range: null,
                title: "音乐模式1或2",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_music_3_or_4",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_music_3_or_4",
                type: "bool",
                range: null,
                title: "音乐模式3或4",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_set_sensitivity",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_set_sensitivity",
                type: "bool",
                range: null,
                title: "设置灵敏度(senc:0-100)",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_increase_sensitivity",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_increase_sensitivity",
                type: "bool",
                range: null,
                title: "灵敏度+",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_decrease_sensitivity",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_decrease_sensitivity",
                type: "bool",
                range: null,
                title: "灵敏度-",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_enter_music_increase_sensitivity",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_enter_music_increase_sensitivity",
                type: "bool",
                range: null,
                title: "灵敏度+(强制进音乐模式)",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_enter_music_decrease_sensitivity",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_enter_music_decrease_sensitivity",
                type: "bool",
                range: null,
                title: "灵敏度-(强制进音乐模式)",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_rgb_index",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_rgb_index",
                type: "bool",
                range: null,
                title: "R->G->B",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_rgb_scene_and_off",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_rgb_scene_and_off",
                type: "bool",
                range: null,
                title: "RGB场景",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_7_color_and_scene",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_7_color_and_scene",
                type: "bool",
                range: null,
                title: "7色场景循环",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_7_color",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_7_color",
                type: "bool",
                range: null,
                title: "7色循环",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_on_and_off",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_on_and_off",
                type: "bool",
                range: null,
                title: "开关",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_start_wifi_config",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_start_wifi_config",
                type: "bool",
                range: null,
                title: "进入配网",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
              {
                id: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_M",
                help: null,
                name: "CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_M",
                type: "bool",
                range: null,
                title: "循环",
                children: [],
                depends_on: "<choice CL_KEY_CONTROL_-id-_CLICK_FUN>",
              },
            ],
            placement: "middle",
            depends_on: "CL_KEY_CONTROL_MODEL_NONE",
          },
          {
            id: "CL_REMOTE_CONTROL_-id-_FUN_arg",
            help: null,
            name: "CL_REMOTE_CONTROL_-id-_FUN_arg",
            type: "string",
            range: null,
            title: "",
            default: '""',
            children: [],
            placement: "right",
            depends_on:
              "(CL_KEY_CONTROL_-id-_CLICK_FUN_fun_bright_change || CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_set_music_mode || CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_set_countdown || CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_set_bright || CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_set_color || CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_set_scene_mode || CL_KEY_CONTROL_-id-_CLICK_FUN_fun_btn_remote_fun_set_sensitivity) && CL_KEY_CONTROL_MODEL_NONE",
          },
        ],
        depends_on: "CL_KEY_CONTROL_MODEL_NONE",
      },
    ],
    depends_on: null,
  },
];
