/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BoolComponent: typeof import('./components/boolComponent.vue')['default']
    ChoiceComponent: typeof import('./components/choiceComponent.vue')['default']
    Helper: typeof import('./components/helper.vue')['default']
    IntComponent: typeof import('./components/intComponent.vue')['default']
    Menu2Component: typeof import('./components/menu2Component.vue')['default']
    MenuComponent: typeof import('./components/menuComponent.vue')['default']
    PullList: typeof import('./components/pullList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StringComponent: typeof import('./components/stringComponent.vue')['default']
  }
}
